 [                                                                                           
   {                                                                                         
     "Plan": {                                                                               
       "Node Type": "Aggregate",                                                             
       "Strategy": "Plain",                                                                  
       "Partial Mode": "Simple",                                                             
       "Parallel Aware": false,                                                              
       "Startup Cost": 12886.65,                                                             
       "Total Cost": 12886.65,                                                               
       "Plan Rows": 1,                                                                       
       "Plan Width": 96,                                                                     
       "Actual Startup Time": 93263.369,                                                     
       "Actual Total Time": 93263.369,                                                       
       "Actual Rows": 1,                                                                     
       "Actual Loops": 1,                                                                    
       "Shared Hit Blocks": 437152,                                                          
       "Shared Read Blocks": 45680,                                                          
       "Shared Dirtied Blocks": 0,                                                           
       "Shared Written Blocks": 0,                                                           
       "Local Hit Blocks": 0,                                                                
       "Local Read Blocks": 0,                                                               
       "Local Dirtied Blocks": 0,                                                            
       "Local Written Blocks": 0,                                                            
       "Temp Read Blocks": 0,                                                                
       "Temp Written Blocks": 0,                                                             
       "Plans": [                                                                            
         {                                                                                   
           "Node Type": "Nested Loop",                                                       
           "Parent Relationship": "Outer",                                                   
           "Parallel Aware": false,                                                          
           "Join Type": "Inner",                                                             
           "Startup Cost": 0.08,                                                             
           "Total Cost": 12886.65,                                                           
           "Plan Rows": 1,                                                                   
           "Plan Width": 42,                                                                 
           "Actual Startup Time": 4572.438,                                                  
           "Actual Total Time": 93261.229,                                                   
           "Actual Rows": 397,                                                               
           "Actual Loops": 1,                                                                
           "Inner Unique": true,                                                             
           "Shared Hit Blocks": 437152,                                                      
           "Shared Read Blocks": 45680,                                                      
           "Shared Dirtied Blocks": 0,                                                       
           "Shared Written Blocks": 0,                                                       
           "Local Hit Blocks": 0,                                                            
           "Local Read Blocks": 0,                                                           
           "Local Dirtied Blocks": 0,                                                        
           "Local Written Blocks": 0,                                                        
           "Temp Read Blocks": 0,                                                            
           "Temp Written Blocks": 0,                                                         
           "Plans": [                                                                        
             {                                                                               
               "Node Type": "Nested Loop",                                                   
               "Parent Relationship": "Outer",                                               
               "Parallel Aware": false,                                                      
               "Join Type": "Inner",                                                         
               "Startup Cost": 0.07,                                                         
               "Total Cost": 12886.63,                                                       
               "Plan Rows": 5,                                                               
               "Plan Width": 46,                                                             
               "Actual Startup Time": 4572.374,                                              
               "Actual Total Time": 93255.040,                                               
               "Actual Rows": 397,                                                           
               "Actual Loops": 1,                                                            
               "Inner Unique": false,                                                        
               "Join Filter": "(t.id = mi.movie_id)",                                        
               "Rows Removed by Join Filter": 0,                                             
               "Shared Hit Blocks": 436358,                                                  
               "Shared Read Blocks": 45680,                                                  
               "Shared Dirtied Blocks": 0,                                                   
               "Shared Written Blocks": 0,                                                   
               "Local Hit Blocks": 0,                                                        
               "Local Read Blocks": 0,                                                       
               "Local Dirtied Blocks": 0,                                                    
               "Local Written Blocks": 0,                                                    
               "Temp Read Blocks": 0,                                                        
               "Temp Written Blocks": 0,                                                     
               "Plans": [                                                                    
                 {                                                                           
                   "Node Type": "Nested Loop",                                               
                   "Parent Relationship": "Outer",                                           
                   "Parallel Aware": false,                                                  
                   "Join Type": "Inner",                                                     
                   "Startup Cost": 0.06,                                                     
                   "Total Cost": 12882.06,                                                   
                   "Plan Rows": 18,                                                          
                   "Plan Width": 54,                                                         
                   "Actual Startup Time": 449.443,                                           
                   "Actual Total Time": 56311.548,                                           
                   "Actual Rows": 5674,                                                      
                   "Actual Loops": 1,                                                        
                   "Inner Unique": true,                                                     
                   "Join Filter": "(mi_idx.movie_id = t.id)",                                
                   "Rows Removed by Join Filter": 0,                                         
                   "Shared Hit Blocks": 368460,                                              
                   "Shared Read Blocks": 33938,                                              
                   "Shared Dirtied Blocks": 0,                                               
                   "Shared Written Blocks": 0,                                               
                   "Local Hit Blocks": 0,                                                    
                   "Local Read Blocks": 0,                                                   
                   "Local Dirtied Blocks": 0,                                                
                   "Local Written Blocks": 0,                                                
                   "Temp Read Blocks": 0,                                                    
                   "Temp Written Blocks": 0,                                                 
                   "Plans": [                                                                
                     {                                                                       
                       "Node Type": "Nested Loop",                                           
                       "Parent Relationship": "Outer",                                       
                       "Parallel Aware": false,                                              
                       "Join Type": "Inner",                                                 
                       "Startup Cost": 0.05,                                                 
                       "Total Cost": 12875.51,                                               
                       "Plan Rows": 102,                                                     
                       "Plan Width": 33,                                                     
                       "Actual Startup Time": 100.847,                                       
                       "Actual Total Time": 33070.968,                                       
                       "Actual Rows": 19791,                                                 
                       "Actual Loops": 1,                                                    
                       "Inner Unique": true,                                                 
                       "Shared Hit Blocks": 298833,                                          
                       "Shared Read Blocks": 24329,                                          
                       "Shared Dirtied Blocks": 0,                                           
                       "Shared Written Blocks": 0,                                           
                       "Local Hit Blocks": 0,                                                
                       "Local Read Blocks": 0,                                               
                       "Local Dirtied Blocks": 0,                                            
                       "Local Written Blocks": 0,                                            
                       "Temp Read Blocks": 0,                                                
                       "Temp Written Blocks": 0,                                             
                       "Plans": [                                                            
                         {                                                                   
                           "Node Type": "Nested Loop",                                       
                           "Parent Relationship": "Outer",                                   
                           "Parallel Aware": false,                                          
                           "Join Type": "Inner",                                             
                           "Startup Cost": 0.04,                                             
                           "Total Cost": 12870.49,                                           
                           "Plan Rows": 282,                                                 
                           "Plan Width": 18,                                                 
                           "Actual Startup Time": 24.231,                                    
                           "Actual Total Time": 13705.053,                                   
                           "Actual Rows": 24233,                                             
                           "Actual Loops": 1,                                                
                           "Inner Unique": true,                                             
                           "Shared Hit Blocks": 204504,                                      
                           "Shared Read Blocks": 21334,                                      
                           "Shared Dirtied Blocks": 0,                                       
                           "Shared Written Blocks": 0,                                       
                           "Local Hit Blocks": 0,                                            
                           "Local Read Blocks": 0,                                           
                           "Local Dirtied Blocks": 0,                                        
                           "Local Written Blocks": 0,                                        
                           "Temp Read Blocks": 0,                                            
                           "Temp Written Blocks": 0,                                         
                           "Plans": [                                                        
                             {                                                               
                               "Node Type": "Nested Loop",                                   
                               "Parent Relationship": "Outer",                               
                               "Parallel Aware": false,                                      
                               "Join Type": "Inner",                                         
                               "Startup Cost": 0.03,                                         
                               "Total Cost": 12865.61,                                       
                               "Plan Rows": 1129,                                            
                               "Plan Width": 22,                                             
                               "Actual Startup Time": 0.216,                                 
                               "Actual Total Time": 13419.140,                               
                               "Actual Rows": 64707,                                         
                               "Actual Loops": 1,                                            
                               "Inner Unique": false,                                        
                               "Shared Hit Blocks": 75090,                                   
                               "Shared Read Blocks": 21334,                                  
                               "Shared Dirtied Blocks": 0,                                   
                               "Shared Written Blocks": 0,                                   
                               "Local Hit Blocks": 0,                                        
                               "Local Read Blocks": 0,                                       
                               "Local Dirtied Blocks": 0,                                    
                               "Local Written Blocks": 0,                                    
                               "Temp Read Blocks": 0,                                        
                               "Temp Written Blocks": 0,                                     
                               "Plans": [                                                    
                                 {                                                           
                                   "Node Type": "Nested Loop",                               
                                   "Parent Relationship": "Outer",                           
                                   "Parallel Aware": false,                                  
                                   "Join Type": "Inner",                                     
                                   "Startup Cost": 0.02,                                     
                                   "Total Cost": 12156.13,                                   
                                   "Plan Rows": 468,                                         
                                   "Plan Width": 10,                                         
                                   "Actual Startup Time": 0.189,                             
                                   "Actual Total Time": 3151.315,                            
                                   "Actual Rows": 15849,                                     
                                   "Actual Loops": 1,                                        
                                   "Inner Unique": true,                                     
                                   "Join Filter": "(it.id = mi_idx.info_type_id)",          
                                   "Rows Removed by Join Filter": 37013,                     
                                   "Shared Hit Blocks": 13572,                               
                                   "Shared Read Blocks": 12221,                              
                                   "Shared Dirtied Blocks": 0,                               
                                   "Shared Written Blocks": 0,                               
                                   "Local Hit Blocks": 0,                                    
                                   "Local Read Blocks": 0,                                   
                                   "Local Dirtied Blocks": 0,                                
                                   "Local Written Blocks": 0,                                
                                   "Temp Read Blocks": 0,                                    
                                   "Temp Written Blocks": 0,                                 
                                   "Plans": [                                                
                                     {                                                       
                                       "Node Type": "Index Scan",                            
                                       "Parent Relationship": "Outer",                       
                                       "Parallel Aware": false,                              
                                       "Scan Direction": "Forward",                          
                                       "Index Name": "movie_id_movie_info_idx",              
                                       "Relation Name": "movie_info_idx",                    
                                       "Alias": "mi_idx",                                    
                                       "Startup Cost": 0.01,                                 
                                       "Total Cost": 12138.14,                               
                                       "Plan Rows": 52860,                                   
                                       "Plan Width": 14,                                     
                                       "Actual Startup Time": 0.126,                         
                                       "Actual Total Time": 3082.909,                        
                                       "Actual Rows": 52862,                                 
                                       "Actual Loops": 1,                                    
                                       "Filter": "(info > '8.0'::text)",                     
                                       "Rows Removed by Filter": 1327173,                    
                                       "Shared Hit Blocks": 13571,                           
                                       "Shared Read Blocks": 12220,                          
                                       "Shared Dirtied Blocks": 0,                           
                                       "Shared Written Blocks": 0,                           
                                       "Local Hit Blocks": 0,                                
                                       "Local Read Blocks": 0,                               
                                       "Local Dirtied Blocks": 0,                            
                                       "Local Written Blocks": 0,                            
                                       "Temp Read Blocks": 0,                                
                                       "Temp Written Blocks": 0                              
                                     },                                                      
                                     {                                                       
                                       "Node Type": "Materialize",                           
                                       "Parent Relationship": "Inner",                       
                                       "Parallel Aware": false,                              
                                       "Startup Cost": 0.00,                                 
                                       "Total Cost": 6.13,                                   
                                       "Plan Rows": 1,                                       
                                       "Plan Width": 4,                                      
                                       "Actual Startup Time": 0.000,                         
                                       "Actual Total Time": 0.000,                           
                                       "Actual Rows": 1,                                     
                                       "Actual Loops": 52862,                                
                                       "Shared Hit Blocks": 1,                               
                                       "Shared Read Blocks": 1,                              
                                       "Shared Dirtied Blocks": 0,                           
                                       "Shared Written Blocks": 0,                           
                                       "Local Hit Blocks": 0,                                
                                       "Local Read Blocks": 0,                               
                                       "Local Dirtied Blocks": 0,                            
                                       "Local Written Blocks": 0,                            
                                       "Temp Read Blocks": 0,                                
                                       "Temp Written Blocks": 0,                             
                                       "Plans": [                                            
                                         {                                                   
                                           "Node Type": "Index Scan",                        
                                           "Parent Relationship": "Outer",                   
                                           "Parallel Aware": false,                          
                                           "Scan Direction": "Forward",                      
                                           "Index Name": "info_type_info_key",               
                                           "Relation Name": "info_type",                     
                                           "Alias": "it",                                   
                                           "Startup Cost": 0.00,                             
                                           "Total Cost": 6.13,                               
                                           "Plan Rows": 1,                                   
                                           "Plan Width": 4,                                  
                                           "Actual Startup Time": 0.046,                     
                                           "Actual Total Time": 0.048,                       
                                           "Actual Rows": 1,                                 
                                           "Actual Loops": 1,                                
                                           "Index Cond": "((info)::text = 'rating'::text)",  
                                           "Rows Removed by Index Recheck": 0,               
                                           "Shared Hit Blocks": 1,                           
                                           "Shared Read Blocks": 1,                          
                                           "Shared Dirtied Blocks": 0,                       
                                           "Shared Written Blocks": 0,                       
                                           "Local Hit Blocks": 0,                            
                                           "Local Read Blocks": 0,                           
                                           "Local Dirtied Blocks": 0,                        
                                           "Local Written Blocks": 0,                        
                                           "Temp Read Blocks": 0,                            
                                           "Temp Written Blocks": 0                          
                                         }                                                   
                                       ]                                                     
                                     }                                                       
                                   ]                                                         
                                 },                                                          
                                 {                                                           
                                   "Node Type": "Index Scan",                                
                                   "Parent Relationship": "Inner",                           
                                   "Parallel Aware": false,                                  
                                   "Scan Direction": "Forward",                              
                                   "Index Name": "movie_id_movie_companies",                 
                                   "Relation Name": "movie_companies",                       
                                   "Alias": "mc",                                            
                                   "Startup Cost": 0.01,                                     
                                   "Total Cost": 1.52,                                       
                                   "Plan Rows": 2,                                           
                                   "Plan Width": 12,                                         
                                   "Actual Startup Time": 0.491,                             
                                   "Actual Total Time": 0.644,                               
                                   "Actual Rows": 4,                                         
                                   "Actual Loops": 15849,                                    
                                   "Index Cond": "(movie_id = mi_idx.movie_id)",             
                                   "Rows Removed by Index Recheck": 0,                       
                                   "Shared Hit Blocks": 61518,                               
                                   "Shared Read Blocks": 9113,                               
                                   "Shared Dirtied Blocks": 0,                               
                                   "Shared Written Blocks": 0,                               
                                   "Local Hit Blocks": 0,                                    
                                   "Local Read Blocks": 0,                                   
                                   "Local Dirtied Blocks": 0,                                
                                   "Local Written Blocks": 0,                                
                                   "Temp Read Blocks": 0,                                    
                                   "Temp Written Blocks": 0                                  
                                 }                                                           
                               ]                                                             
                             },                                                              
                             {                                                               
                               "Node Type": "Index Scan",                                    
                               "Parent Relationship": "Inner",                               
                               "Parallel Aware": false,                                      
                               "Scan Direction": "Forward",                                  
                               "Index Name": "company_type_pkey",                            
                               "Relation Name": "company_type",                              
                               "Alias": "ct",                                                
                               "Startup Cost": 0.00,                                         
                               "Total Cost": 0.00,                                           
                               "Plan Rows": 1,                                               
                               "Plan Width": 4,                                              
                               "Actual Startup Time": 0.003,                                 
                               "Actual Total Time": 0.003,                                   
                               "Actual Rows": 0,                                             
                               "Actual Loops": 64707,                                        
                               "Index Cond": "(id = mc.company_type_id)",                    
                               "Rows Removed by Index Recheck": 0,                           
                               "Filter": "((kind)::text = 'production companies'::text)",    
                               "Rows Removed by Filter": 1,                                  
                               "Shared Hit Blocks": 129414,                                  
                               "Shared Read Blocks": 0,                                      
                               "Shared Dirtied Blocks": 0,                                   
                               "Shared Written Blocks": 0,                                   
                               "Local Hit Blocks": 0,                                        
                               "Local Read Blocks": 0,                                       
                               "Local Dirtied Blocks": 0,                                    
                               "Local Written Blocks": 0,                                    
                               "Temp Read Blocks": 0,                                        
                               "Temp Written Blocks": 0                                      
                             }                                                               
                           ]                                                                 
                         },                                                                  
                         {                                                                   
                           "Node Type": "Index Scan",                                        
                           "Parent Relationship": "Inner",                                   
                           "Parallel Aware": false,                                          
                           "Scan Direction": "Forward",                                      
                           "Index Name": "company_name_pkey",                                
                           "Relation Name": "company_name",                                  
                           "Alias": "cn",                                                    
                           "Startup Cost": 0.01,                                             
                           "Total Cost": 0.02,                                               
                           "Plan Rows": 1,                                                   
                           "Plan Width": 23,                                                 
                           "Actual Startup Time": 0.798,                                     
                           "Actual Total Time": 0.798,                                       
                           "Actual Rows": 1,                                                 
                           "Actual Loops": 24233,                                            
                           "Index Cond": "(id = mc.company_id)",                             
                           "Rows Removed by Index Recheck": 0,                               
                           "Filter": "((country_code)::text = '[us]'::text)",                
                           "Rows Removed by Filter": 0,                                      
                           "Shared Hit Blocks": 94329,                                       
                           "Shared Read Blocks": 2995,                                       
                           "Shared Dirtied Blocks": 0,                                       
                           "Shared Written Blocks": 0,                                       
                           "Local Hit Blocks": 0,                                            
                           "Local Read Blocks": 0,                                           
                           "Local Dirtied Blocks": 0,                                        
                           "Local Written Blocks": 0,                                        
                           "Temp Read Blocks": 0,                                            
                           "Temp Written Blocks": 0                                          
                         }                                                                   
                       ]                                                                     
                     },                                                                      
                     {                                                                       
                       "Node Type": "Index Scan",                                            
                       "Parent Relationship": "Inner",                                       
                       "Parallel Aware": false,                                              
                       "Scan Direction": "Forward",                                          
                       "Index Name": "title_idx_id",                                         
                       "Relation Name": "title",                                             
                       "Alias": "t",                                                         
                       "Startup Cost": 0.01,                                                 
                       "Total Cost": 0.06,                                                   
                       "Plan Rows": 1,                                                       
                       "Plan Width": 21,                                                     
                       "Actual Startup Time": 1.173,                                         
                       "Actual Total Time": 1.173,                                           
                       "Actual Rows": 0,                                                     
                       "Actual Loops": 19791,                                                
                       "Index Cond": "(id = mc.movie_id)",                                   
                       "Rows Removed by Index Recheck": 0,                                   
                       "Filter": "((production_year >= 2005) AND (production_year <= 2008))",
                       "Rows Removed by Filter": 1,                                          
                       "Shared Hit Blocks": 69627,                                           
                       "Shared Read Blocks": 9609,                                           
                       "Shared Dirtied Blocks": 0,                                           
                       "Shared Written Blocks": 0,                                           
                       "Local Hit Blocks": 0,                                                
                       "Local Read Blocks": 0,                                               
                       "Local Dirtied Blocks": 0,                                            
                       "Local Written Blocks": 0,                                            
                       "Temp Read Blocks": 0,                                                
                       "Temp Written Blocks": 0                                              
                     }                                                                       
                   ]                                                                         
                 },                                                                          
                 {                                                                           
                   "Node Type": "Index Scan",                                                
                   "Parent Relationship": "Inner",                                           
                   "Parallel Aware": false,                                                  
                   "Scan Direction": "Forward",                                              
                   "Index Name": "movie_id_movie_info",                                      
                   "Relation Name": "movie_info",                                            
                   "Alias": "mi",                                                            
                   "Startup Cost": 0.01,                                                     
                   "Total Cost": 0.25,                                                       
                   "Plan Rows": 1,                                                           
                   "Plan Width": 8,                                                          
                   "Actual Startup Time": 6.505,                                             
                   "Actual Total Time": 6.509,                                               
                   "Actual Rows": 0,                                                         
                   "Actual Loops": 5674,                                                     
                   "Index Cond": "(movie_id = mc.movie_id)",                                 
                   "Rows Removed by Index Recheck": 0,                                       
                   "Filter": "(info = ANY ('{Drama,Horror}'::text[]))",                      
                   "Rows Removed by Filter": 28,                                             
                   "Shared Hit Blocks": 67898,                                               
                   "Shared Read Blocks": 11742,                                              
                   "Shared Dirtied Blocks": 0,                                               
                   "Shared Written Blocks": 0,                                               
                   "Local Hit Blocks": 0,                                                    
                   "Local Read Blocks": 0,                                                   
                   "Local Dirtied Blocks": 0,                                                
                   "Local Written Blocks": 0,                                                
                   "Temp Read Blocks": 0,                                                    
                   "Temp Written Blocks": 0                                                  
                 }                                                                           
               ]                                                                             
             },                                                                              
             {                                                                               
               "Node Type": "Index Scan",                                                    
               "Parent Relationship": "Inner",                                               
               "Parallel Aware": false,                                                      
               "Scan Direction": "Forward",                                                  
               "Index Name": "info_type_pkey",                                               
               "Relation Name": "info_type",                                                 
               "Alias": "it",                                                               
               "Startup Cost": 0.00,                                                         
               "Total Cost": 0.00,                                                           
               "Plan Rows": 1,                                                               
               "Plan Width": 4,                                                              
               "Actual Startup Time": 0.010,                                                 
               "Actual Total Time": 0.010,                                                   
               "Actual Rows": 1,                                                             
               "Actual Loops": 397,                                                          
               "Index Cond": "(id = mi.info_type_id)",                                       
               "Rows Removed by Index Recheck": 0,                                           
               "Filter": "((info)::text = 'genres'::text)",                                  
               "Rows Removed by Filter": 0,                                                  
               "Shared Hit Blocks": 794,                                                     
               "Shared Read Blocks": 0,                                                      
               "Shared Dirtied Blocks": 0,                                                   
               "Shared Written Blocks": 0,                                                   
               "Local Hit Blocks": 0,                                                        
               "Local Read Blocks": 0,                                                       
               "Local Dirtied Blocks": 0,                                                    
               "Local Written Blocks": 0,                                                    
               "Temp Read Blocks": 0,                                                        
               "Temp Written Blocks": 0                                                      
             }                                                                               
           ]                                                                                 
         }                                                                                   
       ]                                                                                     
     },                                                                                      
     "Planning Time": 5242.961,                                                              
     "Triggers": [                                                                           
     ],                                                                                      
     "Execution Time": 93286.742                                                             
   }                                                                                         
 ]
