 [                                                                                                                                               
   {                                                                                                                                             
     "Plan": {                                                                                                                                   
       "Node Type": "Aggregate",                                                                                                                 
       "Strategy": "Plain",                                                                                                                      
       "Partial Mode": "Simple",                                                                                                                 
       "Parallel Aware": false,                                                                                                                  
       "Startup Cost": 908.24,                                                                                                                   
       "Total Cost": 908.24,                                                                                                                     
       "Plan Rows": 1,                                                                                                                           
       "Plan Width": 128,                                                                                                                        
       "Actual Startup Time": 1661427.240,                                                                                                       
       "Actual Total Time": 1661427.241,                                                                                                         
       "Actual Rows": 1,                                                                                                                         
       "Actual Loops": 1,                                                                                                                        
       "Shared Hit Blocks": 4767213,                                                                                                             
       "Shared Read Blocks": 369552,                                                                                                             
       "Shared Dirtied Blocks": 0,                                                                                                               
       "Shared Written Blocks": 0,                                                                                                               
       "Local Hit Blocks": 0,                                                                                                                    
       "Local Read Blocks": 0,                                                                                                                   
       "Local Dirtied Blocks": 0,                                                                                                                
       "Local Written Blocks": 0,                                                                                                                
       "Temp Read Blocks": 0,                                                                                                                    
       "Temp Written Blocks": 0,                                                                                                                 
       "Plans": [                                                                                                                                
         {                                                                                                                                       
           "Node Type": "Nested Loop",                                                                                                           
           "Parent Relationship": "Outer",                                                                                                       
           "Parallel Aware": false,                                                                                                              
           "Join Type": "Inner",                                                                                                                 
           "Startup Cost": 0.11,                                                                                                                 
           "Total Cost": 908.24,                                                                                                                 
           "Plan Rows": 1,                                                                                                                       
           "Plan Width": 80,                                                                                                                     
           "Actual Startup Time": 841.900,                                                                                                       
           "Actual Total Time": 1661317.896,                                                                                                     
           "Actual Rows": 26153,                                                                                                                 
           "Actual Loops": 1,                                                                                                                    
           "Inner Unique": true,                                                                                                                 
           "Shared Hit Blocks": 4767213,                                                                                                         
           "Shared Read Blocks": 369552,                                                                                                         
           "Shared Dirtied Blocks": 0,                                                                                                           
           "Shared Written Blocks": 0,                                                                                                           
           "Local Hit Blocks": 0,                                                                                                                
           "Local Read Blocks": 0,                                                                                                               
           "Local Dirtied Blocks": 0,                                                                                                            
           "Local Written Blocks": 0,                                                                                                            
           "Temp Read Blocks": 0,                                                                                                                
           "Temp Written Blocks": 0,                                                                                                             
           "Plans": [                                                                                                                            
             {                                                                                                                                   
               "Node Type": "Nested Loop",                                                                                                       
               "Parent Relationship": "Outer",                                                                                                   
               "Parallel Aware": false,                                                                                                          
               "Join Type": "Inner",                                                                                                             
               "Startup Cost": 0.10,                                                                                                             
               "Total Cost": 908.21,                                                                                                             
               "Plan Rows": 1,                                                                                                                   
               "Plan Width": 84,                                                                                                                 
               "Actual Startup Time": 841.849,                                                                                                   
               "Actual Total Time": 1661086.885,                                                                                                 
               "Actual Rows": 29015,                                                                                                             
               "Actual Loops": 1,                                                                                                                
               "Inner Unique": false,                                                                                                            
               "Join Filter": "(t.id = mi.movie_id)",                                                                                            
               "Rows Removed by Join Filter": 0,                                                                                                 
               "Shared Hit Blocks": 4709183,                                                                                                     
               "Shared Read Blocks": 369552,                                                                                                     
               "Shared Dirtied Blocks": 0,                                                                                                       
               "Shared Written Blocks": 0,                                                                                                       
               "Local Hit Blocks": 0,                                                                                                            
               "Local Read Blocks": 0,                                                                                                           
               "Local Dirtied Blocks": 0,                                                                                                        
               "Local Written Blocks": 0,                                                                                                        
               "Temp Read Blocks": 0,                                                                                                            
               "Temp Written Blocks": 0,                                                                                                         
               "Plans": [                                                                                                                        
                 {                                                                                                                               
                   "Node Type": "Nested Loop",                                                                                                   
                   "Parent Relationship": "Outer",                                                                                               
                   "Parallel Aware": false,                                                                                                      
                   "Join Type": "Inner",                                                                                                         
                   "Startup Cost": 0.09,                                                                                                         
                   "Total Cost": 907.90,                                                                                                         
                   "Plan Rows": 2,                                                                                                               
                   "Plan Width": 54,                                                                                                             
                   "Actual Startup Time": 761.598,                                                                                               
                   "Actual Total Time": 1392295.460,                                                                                             
                   "Actual Rows": 22670,                                                                                                         
                   "Actual Loops": 1,                                                                                                            
                   "Inner Unique": true,                                                                                                         
                   "Join Filter": "(mi_idx.movie_id = t.id)",                                                                                    
                   "Rows Removed by Join Filter": 0,                                                                                             
                   "Shared Hit Blocks": 4352532,                                                                                                 
                   "Shared Read Blocks": 289665,                                                                                                 
                   "Shared Dirtied Blocks": 0,                                                                                                   
                   "Shared Written Blocks": 0,                                                                                                   
                   "Local Hit Blocks": 0,                                                                                                        
                   "Local Read Blocks": 0,                                                                                                       
                   "Local Dirtied Blocks": 0,                                                                                                    
                   "Local Written Blocks": 0,                                                                                                    
                   "Temp Read Blocks": 0,                                                                                                        
                   "Temp Written Blocks": 0,                                                                                                     
                   "Plans": [                                                                                                                    
                     {                                                                                                                           
                       "Node Type": "Nested Loop",                                                                                               
                       "Parent Relationship": "Outer",                                                                                           
                       "Parallel Aware": false,                                                                                                  
                       "Join Type": "Inner",                                                                                                     
                       "Startup Cost": 0.08,                                                                                                     
                       "Total Cost": 907.82,                                                                                                     
                       "Plan Rows": 2,                                                                                                           
                       "Plan Width": 33,                                                                                                         
                       "Actual Startup Time": 715.626,                                                                                           
                       "Actual Total Time": 1326404.774,                                                                                         
                       "Actual Rows": 22670,                                                                                                     
                       "Actual Loops": 1,                                                                                                        
                       "Inner Unique": true,                                                                                                     
                       "Shared Hit Blocks": 4271934,                                                                                             
                       "Shared Read Blocks": 279548,                                                                                             
                       "Shared Dirtied Blocks": 0,                                                                                               
                       "Shared Written Blocks": 0,                                                                                               
                       "Local Hit Blocks": 0,                                                                                                    
                       "Local Read Blocks": 0,                                                                                                   
                       "Local Dirtied Blocks": 0,                                                                                                
                       "Local Written Blocks": 0,                                                                                                
                       "Temp Read Blocks": 0,                                                                                                    
                       "Temp Written Blocks": 0,                                                                                                 
                       "Plans": [                                                                                                                
                         {                                                                                                                       
                           "Node Type": "Nested Loop",                                                                                           
                           "Parent Relationship": "Outer",                                                                                       
                           "Parallel Aware": false,                                                                                              
                           "Join Type": "Inner",                                                                                                 
                           "Startup Cost": 0.06,                                                                                                 
                           "Total Cost": 906.88,                                                                                                 
                           "Plan Rows": 5,                                                                                                       
                           "Plan Width": 22,                                                                                                     
                           "Actual Startup Time": 699.904,                                                                                       
                           "Actual Total Time": 1187742.997,                                                                                     
                           "Actual Rows": 38991,                                                                                                 
                           "Actual Loops": 1,                                                                                                    
                           "Inner Unique": false,                                                                                                
                           "Join Filter": "(mi_idx.movie_id = ci.movie_id)",                                                                     
                           "Rows Removed by Join Filter": 0,                                                                                     
                           "Shared Hit Blocks": 4133807,                                                                                         
                           "Shared Read Blocks": 261473,                                                                                         
                           "Shared Dirtied Blocks": 0,                                                                                           
                           "Shared Written Blocks": 0,                                                                                           
                           "Local Hit Blocks": 0,                                                                                                
                           "Local Read Blocks": 0,                                                                                               
                           "Local Dirtied Blocks": 0,                                                                                            
                           "Local Written Blocks": 0,                                                                                            
                           "Temp Read Blocks": 0,                                                                                                
                           "Temp Written Blocks": 0,                                                                                             
                           "Plans": [                                                                                                            
                             {                                                                                                                   
                               "Node Type": "Nested Loop",                                                                                       
                               "Parent Relationship": "Outer",                                                                                   
                               "Parallel Aware": false,                                                                                          
                               "Join Type": "Inner",                                                                                             
                               "Startup Cost": 0.04,                                                                                             
                               "Total Cost": 905.29,                                                                                             
                               "Plan Rows": 6,                                                                                                   
                               "Plan Width": 14,                                                                                                 
                               "Actual Startup Time": 46.982,                                                                                    
                               "Actual Total Time": 37874.952,                                                                                   
                               "Actual Rows": 63701,                                                                                             
                               "Actual Loops": 1,                                                                                                
                               "Inner Unique": true,                                                                                             
                               "Shared Hit Blocks": 701677,                                                                                      
                               "Shared Read Blocks": 31124,                                                                                      
                               "Shared Dirtied Blocks": 0,                                                                                       
                               "Shared Written Blocks": 0,                                                                                       
                               "Local Hit Blocks": 0,                                                                                            
                               "Local Read Blocks": 0,                                                                                           
                               "Local Dirtied Blocks": 0,                                                                                        
                               "Local Written Blocks": 0,                                                                                        
                               "Temp Read Blocks": 0,                                                                                            
                               "Temp Written Blocks": 0,                                                                                         
                               "Plans": [                                                                                                        
                                 {                                                                                                               
                                   "Node Type": "Nested Loop",                                                                                   
                                   "Parent Relationship": "Outer",                                                                               
                                   "Parallel Aware": false,                                                                                      
                                   "Join Type": "Inner",                                                                                         
                                   "Startup Cost": 0.04,                                                                                         
                                   "Total Cost": 901.96,                                                                                         
                                   "Plan Rows": 710,                                                                                             
                                   "Plan Width": 18,                                                                                             
                                   "Actual Startup Time": 46.945,                                                                                
                                   "Actual Total Time": 36598.390,                                                                               
                                   "Actual Rows": 191689,                                                                                        
                                   "Actual Loops": 1,                                                                                            
                                   "Inner Unique": false,                                                                                        
                                   "Shared Hit Blocks": 318299,                                                                                  
                                   "Shared Read Blocks": 31124,                                                                                  
                                   "Shared Dirtied Blocks": 0,                                                                                   
                                   "Shared Written Blocks": 0,                                                                                   
                                   "Local Hit Blocks": 0,                                                                                        
                                   "Local Read Blocks": 0,                                                                                       
                                   "Local Dirtied Blocks": 0,                                                                                    
                                   "Local Written Blocks": 0,                                                                                    
                                   "Temp Read Blocks": 0,                                                                                        
                                   "Temp Written Blocks": 0,                                                                                     
                                   "Plans": [                                                                                                    
                                     {                                                                                                           
                                       "Node Type": "Nested Loop",                                                                               
                                       "Parent Relationship": "Outer",                                                                           
                                       "Parallel Aware": false,                                                                                  
                                       "Join Type": "Inner",                                                                                     
                                       "Startup Cost": 0.03,                                                                                     
                                       "Total Cost": 896.69,                                                                                     
                                       "Plan Rows": 236,                                                                                         
                                       "Plan Width": 4,                                                                                          
                                       "Actual Startup Time": 46.434,                                                                            
                                       "Actual Total Time": 17151.050,                                                                           
                                       "Actual Rows": 76714,                                                                                     
                                       "Actual Loops": 1,                                                                                        
                                       "Inner Unique": false,                                                                                    
                                       "Shared Hit Blocks": 32400,                                                                               
                                       "Shared Read Blocks": 21098,                                                                              
                                       "Shared Dirtied Blocks": 0,                                                                               
                                       "Shared Written Blocks": 0,                                                                               
                                       "Local Hit Blocks": 0,                                                                                    
                                       "Local Read Blocks": 0,                                                                                   
                                       "Local Dirtied Blocks": 0,                                                                                
                                       "Local Written Blocks": 0,                                                                                
                                       "Temp Read Blocks": 0,                                                                                    
                                       "Temp Written Blocks": 0,                                                                                 
                                       "Plans": [                                                                                                
                                         {                                                                                                       
                                           "Node Type": "Index Scan",                                                                            
                                           "Parent Relationship": "Outer",                                                                       
                                           "Parallel Aware": false,                                                                              
                                           "Scan Direction": "Forward",                                                                          
                                           "Index Name": "keyword_idx_keyword",                                                                  
                                           "Relation Name": "keyword",                                                                           
                                           "Alias": "k",                                                                                         
                                           "Startup Cost": 0.01,                                                                                 
                                           "Total Cost": 42.93,                                                                                  
                                           "Plan Rows": 7,                                                                                       
                                           "Plan Width": 4,                                                                                      
                                           "Actual Startup Time": 23.187,                                                                        
                                           "Actual Total Time": 224.580,                                                                         
                                           "Actual Rows": 7,                                                                                     
                                           "Actual Loops": 1,                                                                                    
                                           "Index Cond": "(keyword = ANY ('{murder,violence,blood,gore,death,female-nudity,hospital}'::text[]))",
                                           "Rows Removed by Index Recheck": 0,                                                                   
                                           "Shared Hit Blocks": 14,                                                                              
                                           "Shared Read Blocks": 17,                                                                             
                                           "Shared Dirtied Blocks": 0,                                                                           
                                           "Shared Written Blocks": 0,                                                                           
                                           "Local Hit Blocks": 0,                                                                                
                                           "Local Read Blocks": 0,                                                                               
                                           "Local Dirtied Blocks": 0,                                                                            
                                           "Local Written Blocks": 0,                                                                            
                                           "Temp Read Blocks": 0,                                                                                
                                           "Temp Written Blocks": 0                                                                              
                                         },                                                                                                      
                                         {                                                                                                       
                                           "Node Type": "Index Scan",                                                                            
                                           "Parent Relationship": "Inner",                                                                       
                                           "Parallel Aware": false,                                                                              
                                           "Scan Direction": "Forward",                                                                          
                                           "Index Name": "keyword_id_movie_keyword",                                                             
                                           "Relation Name": "movie_keyword",                                                                     
                                           "Alias": "mk",                                                                                        
                                           "Startup Cost": 0.01,                                                                                 
                                           "Total Cost": 121.96,                                                                                 
                                           "Plan Rows": 39,                                                                                      
                                           "Plan Width": 8,                                                                                      
                                           "Actual Startup Time": 15.664,                                                                        
                                           "Actual Total Time": 2408.287,                                                                        
                                           "Actual Rows": 10959,                                                                                 
                                           "Actual Loops": 7,                                                                                    
                                           "Index Cond": "(keyword_id = k.id)",                                                                  
                                           "Rows Removed by Index Recheck": 0,                                                                   
                                           "Shared Hit Blocks": 32386,                                                                           
                                           "Shared Read Blocks": 21081,                                                                          
                                           "Shared Dirtied Blocks": 0,                                                                           
                                           "Shared Written Blocks": 0,                                                                           
                                           "Local Hit Blocks": 0,                                                                                
                                           "Local Read Blocks": 0,                                                                               
                                           "Local Dirtied Blocks": 0,                                                                            
                                           "Local Written Blocks": 0,                                                                            
                                           "Temp Read Blocks": 0,                                                                                
                                           "Temp Written Blocks": 0                                                                              
                                         }                                                                                                       
                                       ]                                                                                                         
                                     },                                                                                                          
                                     {                                                                                                           
                                       "Node Type": "Index Scan",                                                                                
                                       "Parent Relationship": "Inner",                                                                           
                                       "Parallel Aware": false,                                                                                  
                                       "Scan Direction": "Forward",                                                                              
                                       "Index Name": "movie_id_movie_info_idx",                                                                  
                                       "Relation Name": "movie_info_idx",                                                                        
                                       "Alias": "mi_idx",                                                                                        
                                       "Startup Cost": 0.01,                                                                                     
                                       "Total Cost": 0.02,                                                                                       
                                       "Plan Rows": 3,                                                                                           
                                       "Plan Width": 14,                                                                                         
                                       "Actual Startup Time": 0.244,                                                                             
                                       "Actual Total Time": 0.250,                                                                               
                                       "Actual Rows": 2,                                                                                         
                                       "Actual Loops": 76714,                                                                                    
                                       "Index Cond": "(movie_id = mk.movie_id)",                                                                 
                                       "Rows Removed by Index Recheck": 0,                                                                       
                                       "Shared Hit Blocks": 285899,                                                                              
                                       "Shared Read Blocks": 10026,                                                                              
                                       "Shared Dirtied Blocks": 0,                                                                               
                                       "Shared Written Blocks": 0,                                                                               
                                       "Local Hit Blocks": 0,                                                                                    
                                       "Local Read Blocks": 0,                                                                                   
                                       "Local Dirtied Blocks": 0,                                                                                
                                       "Local Written Blocks": 0,                                                                                
                                       "Temp Read Blocks": 0,                                                                                    
                                       "Temp Written Blocks": 0                                                                                  
                                     }                                                                                                           
                                   ]                                                                                                             
                                 },                                                                                                              
                                 {                                                                                                               
                                   "Node Type": "Index Scan",                                                                                    
                                   "Parent Relationship": "Inner",                                                                               
                                   "Parallel Aware": false,                                                                                      
                                   "Scan Direction": "Forward",                                                                                  
                                   "Index Name": "info_type_pkey",                                                                               
                                   "Relation Name": "info_type",                                                                                 
                                   "Alias": "it",                                                                                               
                                   "Startup Cost": 0.00,                                                                                         
                                   "Total Cost": 0.00,                                                                                           
                                   "Plan Rows": 1,                                                                                               
                                   "Plan Width": 4,                                                                                              
                                   "Actual Startup Time": 0.005,                                                                                 
                                   "Actual Total Time": 0.005,                                                                                   
                                   "Actual Rows": 0,                                                                                             
                                   "Actual Loops": 191689,                                                                                       
                                   "Index Cond": "(id = mi_idx.info_type_id)",                                                                   
                                   "Rows Removed by Index Recheck": 0,                                                                           
                                   "Filter": "((info)::text = 'votes'::text)",                                                                   
                                   "Rows Removed by Filter": 1,                                                                                  
                                   "Shared Hit Blocks": 383378,                                                                                  
                                   "Shared Read Blocks": 0,                                                                                      
                                   "Shared Dirtied Blocks": 0,                                                                                   
                                   "Shared Written Blocks": 0,                                                                                   
                                   "Local Hit Blocks": 0,                                                                                        
                                   "Local Read Blocks": 0,                                                                                       
                                   "Local Dirtied Blocks": 0,                                                                                    
                                   "Local Written Blocks": 0,                                                                                    
                                   "Temp Read Blocks": 0,                                                                                        
                                   "Temp Written Blocks": 0                                                                                      
                                 }                                                                                                               
                               ]                                                                                                                 
                             },                                                                                                                  
                             {                                                                                                                   
                               "Node Type": "Index Scan",                                                                                        
                               "Parent Relationship": "Inner",                                                                                   
                               "Parallel Aware": false,                                                                                          
                               "Scan Direction": "Forward",                                                                                      
                               "Index Name": "movie_id_cast_info",                                                                               
                               "Relation Name": "cast_info",                                                                                     
                               "Alias": "ci",                                                                                                    
                               "Startup Cost": 0.02,                                                                                             
                               "Total Cost": 0.26,                                                                                               
                               "Plan Rows": 1,                                                                                                   
                               "Plan Width": 8,                                                                                                  
                               "Actual Startup Time": 15.353,                                                                                    
                               "Actual Total Time": 18.049,                                                                                      
                               "Actual Rows": 1,                                                                                                 
                               "Actual Loops": 63701,                                                                                            
                               "Index Cond": "(movie_id = mk.movie_id)",                                                                         
                               "Rows Removed by Index Recheck": 0,                                                                               
                               "Filter": "(note = ANY ('{(writer),\"(head writer)\",\"(written by)\",(story),\"(story editor)\"}'::text[]))",    
                               "Rows Removed by Filter": 54,                                                                                     
                               "Shared Hit Blocks": 3432130,                                                                                     
                               "Shared Read Blocks": 230349,                                                                                     
                               "Shared Dirtied Blocks": 0,                                                                                       
                               "Shared Written Blocks": 0,                                                                                       
                               "Local Hit Blocks": 0,                                                                                            
                               "Local Read Blocks": 0,                                                                                           
                               "Local Dirtied Blocks": 0,                                                                                        
                               "Local Written Blocks": 0,                                                                                        
                               "Temp Read Blocks": 0,                                                                                            
                               "Temp Written Blocks": 0                                                                                          
                             }                                                                                                                   
                           ]                                                                                                                     
                         },                                                                                                                      
                         {                                                                                                                       
                           "Node Type": "Index Scan",                                                                                            
                           "Parent Relationship": "Inner",                                                                                       
                           "Parallel Aware": false,                                                                                              
                           "Scan Direction": "Forward",                                                                                          
                           "Index Name": "name_pkey",                                                                                            
                           "Relation Name": "name",                                                                                              
                           "Alias": "n",                                                                                                         
                           "Startup Cost": 0.01,                                                                                                 
                           "Total Cost": 0.19,                                                                                                   
                           "Plan Rows": 1,                                                                                                       
                           "Plan Width": 19,                                                                                                     
                           "Actual Startup Time": 3.552,                                                                                         
                           "Actual Total Time": 3.552,                                                                                           
                           "Actual Rows": 1,                                                                                                     
                           "Actual Loops": 38991,                                                                                                
                           "Index Cond": "(id = ci.person_id)",                                                                                  
                           "Rows Removed by Index Recheck": 0,                                                                                   
                           "Filter": "((gender)::text = 'm'::text)",                                                                             
                           "Rows Removed by Filter": 0,                                                                                          
                           "Shared Hit Blocks": 138127,                                                                                          
                           "Shared Read Blocks": 18075,                                                                                          
                           "Shared Dirtied Blocks": 0,                                                                                           
                           "Shared Written Blocks": 0,                                                                                           
                           "Local Hit Blocks": 0,                                                                                                
                           "Local Read Blocks": 0,                                                                                               
                           "Local Dirtied Blocks": 0,                                                                                            
                           "Local Written Blocks": 0,                                                                                            
                           "Temp Read Blocks": 0,                                                                                                
                           "Temp Written Blocks": 0                                                                                              
                         }                                                                                                                       
                       ]                                                                                                                         
                     },                                                                                                                          
                     {                                                                                                                           
                       "Node Type": "Index Scan",                                                                                                
                       "Parent Relationship": "Inner",                                                                                           
                       "Parallel Aware": false,                                                                                                  
                       "Scan Direction": "Forward",                                                                                              
                       "Index Name": "title_idx_id",                                                                                             
                       "Relation Name": "title",                                                                                                 
                       "Alias": "t",                                                                                                             
                       "Startup Cost": 0.01,                                                                                                     
                       "Total Cost": 0.04,                                                                                                       
                       "Plan Rows": 1,                                                                                                           
                       "Plan Width": 21,                                                                                                         
                       "Actual Startup Time": 2.900,                                                                                             
                       "Actual Total Time": 2.900,                                                                                               
                       "Actual Rows": 1,                                                                                                         
                       "Actual Loops": 22670,                                                                                                    
                       "Index Cond": "(id = mk.movie_id)",                                                                                       
                       "Rows Removed by Index Recheck": 0,                                                                                       
                       "Shared Hit Blocks": 80598,                                                                                               
                       "Shared Read Blocks": 10117,                                                                                              
                       "Shared Dirtied Blocks": 0,                                                                                               
                       "Shared Written Blocks": 0,                                                                                               
                       "Local Hit Blocks": 0,                                                                                                    
                       "Local Read Blocks": 0,                                                                                                   
                       "Local Dirtied Blocks": 0,                                                                                                
                       "Local Written Blocks": 0,                                                                                                
                       "Temp Read Blocks": 0,                                                                                                    
                       "Temp Written Blocks": 0                                                                                                  
                     }                                                                                                                           
                   ]                                                                                                                             
                 },                                                                                                                              
                 {                                                                                                                               
                   "Node Type": "Index Scan",                                                                                                    
                   "Parent Relationship": "Inner",                                                                                               
                   "Parallel Aware": false,                                                                                                      
                   "Scan Direction": "Forward",                                                                                                  
                   "Index Name": "movie_id_movie_info",                                                                                          
                   "Relation Name": "movie_info",                                                                                                
                   "Alias": "mi",                                                                                                                
                   "Startup Cost": 0.01,                                                                                                         
                   "Total Cost": 0.15,                                                                                                           
                   "Plan Rows": 1,                                                                                                               
                   "Plan Width": 50,                                                                                                             
                   "Actual Startup Time": 11.590,                                                                                                
                   "Actual Total Time": 11.852,                                                                                                  
                   "Actual Rows": 1,                                                                                                             
                   "Actual Loops": 22670,                                                                                                        
                   "Index Cond": "(movie_id = mk.movie_id)",                                                                                     
                   "Rows Removed by Index Recheck": 0,                                                                                           
                   "Filter": "(info = ANY ('{Horror,Action,Sci-Fi,Thriller,Crime,War}'::text[]))",                                               
                   "Rows Removed by Filter": 88,                                                                                                 
                   "Shared Hit Blocks": 356651,                                                                                                  
                   "Shared Read Blocks": 79887,                                                                                                  
                   "Shared Dirtied Blocks": 0,                                                                                                   
                   "Shared Written Blocks": 0,                                                                                                   
                   "Local Hit Blocks": 0,                                                                                                        
                   "Local Read Blocks": 0,                                                                                                       
                   "Local Dirtied Blocks": 0,                                                                                                    
                   "Local Written Blocks": 0,                                                                                                    
                   "Temp Read Blocks": 0,                                                                                                        
                   "Temp Written Blocks": 0                                                                                                      
                 }                                                                                                                               
               ]                                                                                                                                 
             },                                                                                                                                  
             {                                                                                                                                   
               "Node Type": "Index Scan",                                                                                                        
               "Parent Relationship": "Inner",                                                                                                   
               "Parallel Aware": false,                                                                                                          
               "Scan Direction": "Forward",                                                                                                      
               "Index Name": "info_type_pkey",                                                                                                   
               "Relation Name": "info_type",                                                                                                     
               "Alias": "it",                                                                                                                   
               "Startup Cost": 0.00,                                                                                                             
               "Total Cost": 0.00,                                                                                                               
               "Plan Rows": 1,                                                                                                                   
               "Plan Width": 4,                                                                                                                  
               "Actual Startup Time": 0.005,                                                                                                     
               "Actual Total Time": 0.005,                                                                                                       
               "Actual Rows": 1,                                                                                                                 
               "Actual Loops": 29015,                                                                                                            
               "Index Cond": "(id = mi.info_type_id)",                                                                                           
               "Rows Removed by Index Recheck": 0,                                                                                               
               "Filter": "((info)::text = 'genres'::text)",                                                                                      
               "Rows Removed by Filter": 0,                                                                                                      
               "Shared Hit Blocks": 58030,                                                                                                       
               "Shared Read Blocks": 0,                                                                                                          
               "Shared Dirtied Blocks": 0,                                                                                                       
               "Shared Written Blocks": 0,                                                                                                       
               "Local Hit Blocks": 0,                                                                                                            
               "Local Read Blocks": 0,                                                                                                           
               "Local Dirtied Blocks": 0,                                                                                                        
               "Local Written Blocks": 0,                                                                                                        
               "Temp Read Blocks": 0,                                                                                                            
               "Temp Written Blocks": 0                                                                                                          
             }                                                                                                                                   
           ]                                                                                                                                     
         }                                                                                                                                       
       ]                                                                                                                                         
     },                                                                                                                                          
     "Planning Time": 9866.278,                                                                                                                  
     "Triggers": [                                                                                                                               
     ],                                                                                                                                          
     "Execution Time": 1661498.030                                                                                                               
   }                                                                                                                                             
 ]
