 [                                                                                                                  
   {                                                                                                                
     "Plan": {                                                                                                      
       "Node Type": "Aggregate",                                                                                    
       "Strategy": "Plain",                                                                                         
       "Partial Mode": "Simple",                                                                                    
       "Parallel Aware": false,                                                                                     
       "Startup Cost": 690898.93,                                                                                   
       "Total Cost": 690898.93,                                                                                     
       "Plan Rows": 1,                                                                                              
       "Plan Width": 32,                                                                                            
       "Actual Startup Time": 109275.728,                                                                           
       "Actual Total Time": 109275.728,                                                                             
       "Actual Rows": 1,                                                                                            
       "Actual Loops": 1,                                                                                           
       "Shared Hit Blocks": 11720158,                                                                               
       "Shared Read Blocks": 283530,                                                                                
       "Shared Dirtied Blocks": 0,                                                                                  
       "Shared Written Blocks": 0,                                                                                  
       "Local Hit Blocks": 0,                                                                                       
       "Local Read Blocks": 0,                                                                                      
       "Local Dirtied Blocks": 0,                                                                                   
       "Local Written Blocks": 0,                                                                                   
       "Temp Read Blocks": 0,                                                                                       
       "Temp Written Blocks": 0,                                                                                    
       "Plans": [                                                                                                   
         {                                                                                                          
           "Node Type": "Merge Join",                                                                               
           "Parent Relationship": "Outer",                                                                          
           "Parallel Aware": false,                                                                                 
           "Join Type": "Inner",                                                                                    
           "Startup Cost": 70782.72,                                                                                
           "Total Cost": 690898.90,                                                                                 
           "Plan Rows": 364,                                                                                        
           "Plan Width": 17,                                                                                        
           "Actual Startup Time": 36657.262,                                                                        
           "Actual Total Time": 109274.978,                                                                         
           "Actual Rows": 206,                                                                                      
           "Actual Loops": 1,                                                                                       
           "Inner Unique": false,                                                                                   
           "Merge Cond": "(t.id = mi.movie_id)",                                                                    
           "Shared Hit Blocks": 11720158,                                                                           
           "Shared Read Blocks": 283530,                                                                            
           "Shared Dirtied Blocks": 0,                                                                              
           "Shared Written Blocks": 0,                                                                              
           "Local Hit Blocks": 0,                                                                                   
           "Local Read Blocks": 0,                                                                                  
           "Local Dirtied Blocks": 0,                                                                               
           "Local Written Blocks": 0,                                                                               
           "Temp Read Blocks": 0,                                                                                   
           "Temp Written Blocks": 0,                                                                                
           "Plans": [                                                                                               
             {                                                                                                      
               "Node Type": "Sort",                                                                                 
               "Parent Relationship": "Outer",                                                                      
               "Parallel Aware": false,                                                                             
               "Startup Cost": 70782.71,                                                                            
               "Total Cost": 70782.78,                                                                              
               "Plan Rows": 905,                                                                                    
               "Plan Width": 25,                                                                                    
               "Actual Startup Time": 17517.709,                                                                    
               "Actual Total Time": 17519.310,                                                                      
               "Actual Rows": 2234,                                                                                 
               "Actual Loops": 1,                                                                                   
               "Sort Key": ["mk.movie_id"],                                                                         
               "Sort Method": "quicksort",                                                                          
               "Sort Space Used": 279,                                                                              
               "Sort Space Type": "Memory",                                                                         
               "Shared Hit Blocks": 2641013,                                                                        
               "Shared Read Blocks": 81107,                                                                         
               "Shared Dirtied Blocks": 0,                                                                          
               "Shared Written Blocks": 0,                                                                          
               "Local Hit Blocks": 0,                                                                               
               "Local Read Blocks": 0,                                                                              
               "Local Dirtied Blocks": 0,                                                                           
               "Local Written Blocks": 0,                                                                           
               "Temp Read Blocks": 0,                                                                               
               "Temp Written Blocks": 0,                                                                            
               "Plans": [                                                                                           
                 {                                                                                                  
                   "Node Type": "Merge Join",                                                                       
                   "Parent Relationship": "Outer",                                                                  
                   "Parallel Aware": false,                                                                         
                   "Join Type": "Inner",                                                                            
                   "Startup Cost": 68908.60,                                                                        
                   "Total Cost": 70781.33,                                                                          
                   "Plan Rows": 905,                                                                                
                   "Plan Width": 25,                                                                                
                   "Actual Startup Time": 16823.086,                                                                
                   "Actual Total Time": 17506.656,                                                                  
                   "Actual Rows": 2235,                                                                             
                   "Actual Loops": 1,                                                                               
                   "Inner Unique": true,                                                                            
                   "Merge Cond": "(mk.keyword_id = k.id)",                                                          
                   "Shared Hit Blocks": 2641009,                                                                    
                   "Shared Read Blocks": 81107,                                                                     
                   "Shared Dirtied Blocks": 0,                                                                      
                   "Shared Written Blocks": 0,                                                                      
                   "Local Hit Blocks": 0,                                                                           
                   "Local Read Blocks": 0,                                                                          
                   "Local Dirtied Blocks": 0,                                                                       
                   "Local Written Blocks": 0,                                                                       
                   "Temp Read Blocks": 0,                                                                           
                   "Temp Written Blocks": 0,                                                                        
                   "Plans": [                                                                                       
                     {                                                                                              
                       "Node Type": "Sort",                                                                         
                       "Parent Relationship": "Outer",                                                              
                       "Parallel Aware": false,                                                                     
                       "Startup Cost": 68908.58,                                                                    
                       "Total Cost": 69049.30,                                                                      
                       "Plan Rows": 1812426,                                                                        
                       "Plan Width": 29,                                                                            
                       "Actual Startup Time": 16722.699,                                                            
                       "Actual Total Time": 16919.454,                                                              
                       "Actual Rows": 1251254,                                                                      
                       "Actual Loops": 1,                                                                           
                       "Sort Key": ["mk.keyword_id"],                                                               
                       "Sort Method": "quicksort",                                                                  
                       "Sort Space Used": 151439,                                                                   
                       "Sort Space Type": "Memory",                                                                 
                       "Shared Hit Blocks": 2509832,                                                                
                       "Shared Read Blocks": 79675,                                                                 
                       "Shared Dirtied Blocks": 0,                                                                  
                       "Shared Written Blocks": 0,                                                                  
                       "Local Hit Blocks": 0,                                                                       
                       "Local Read Blocks": 0,                                                                      
                       "Local Dirtied Blocks": 0,                                                                   
                       "Local Written Blocks": 0,                                                                   
                       "Temp Read Blocks": 0,                                                                       
                       "Temp Written Blocks": 0,                                                                    
                       "Plans": [                                                                                   
                         {                                                                                          
                           "Node Type": "Merge Join",                                                               
                           "Parent Relationship": "Outer",                                                          
                           "Parallel Aware": false,                                                                 
                           "Join Type": "Inner",                                                                    
                           "Startup Cost": 0.21,                                                                    
                           "Total Cost": 63057.75,                                                                  
                           "Plan Rows": 1812426,                                                                    
                           "Plan Width": 29,                                                                        
                           "Actual Startup Time": 26.230,                                                           
                           "Actual Total Time": 16061.333,                                                          
                           "Actual Rows": 1253091,                                                                  
                           "Actual Loops": 1,                                                                       
                           "Inner Unique": true,                                                                    
                           "Merge Cond": "(mk.movie_id = t.id)",                                                    
                           "Shared Hit Blocks": 2509832,                                                            
                           "Shared Read Blocks": 79675,                                                             
                           "Shared Dirtied Blocks": 0,                                                              
                           "Shared Written Blocks": 0,                                                              
                           "Local Hit Blocks": 0,                                                                   
                           "Local Read Blocks": 0,                                                                  
                           "Local Dirtied Blocks": 0,                                                               
                           "Local Written Blocks": 0,                                                               
                           "Temp Read Blocks": 0,                                                                   
                           "Temp Written Blocks": 0,                                                                
                           "Plans": [                                                                               
                             {                                                                                      
                               "Node Type": "Index Scan",                                                           
                               "Parent Relationship": "Outer",                                                      
                               "Parallel Aware": false,                                                             
                               "Scan Direction": "Forward",                                                         
                               "Index Name": "movie_id_movie_keyword",                                              
                               "Relation Name": "movie_keyword",                                                    
                               "Alias": "mk",                                                                       
                               "Startup Cost": 0.01,                                                                
                               "Total Cost": 39285.80,                                                              
                               "Plan Rows": 4523930,                                                                
                               "Plan Width": 8,                                                                     
                               "Actual Startup Time": 0.025,                                                        
                               "Actual Total Time": 3318.214,                                                       
                               "Actual Rows": 4523930,                                                              
                               "Actual Loops": 1,                                                                   
                               "Shared Hit Blocks": 21643,                                                          
                               "Shared Read Blocks": 36810,                                                         
                               "Shared Dirtied Blocks": 0,                                                          
                               "Shared Written Blocks": 0,                                                          
                               "Local Hit Blocks": 0,                                                               
                               "Local Read Blocks": 0,                                                              
                               "Local Dirtied Blocks": 0,                                                           
                               "Local Written Blocks": 0,                                                           
                               "Temp Read Blocks": 0,                                                               
                               "Temp Written Blocks": 0                                                             
                             },                                                                                     
                             {                                                                                      
                               "Node Type": "Index Scan",                                                           
                               "Parent Relationship": "Inner",                                                      
                               "Parallel Aware": false,                                                             
                               "Scan Direction": "Forward",                                                         
                               "Index Name": "title_idx_id",                                                        
                               "Relation Name": "title",                                                            
                               "Alias": "t",                                                                        
                               "Startup Cost": 0.01,                                                                
                               "Total Cost": 23238.35,                                                              
                               "Plan Rows": 1012920,                                                                
                               "Plan Width": 21,                                                                    
                               "Actual Startup Time": 26.194,                                                       
                               "Actual Total Time": 11481.936,                                                      
                               "Actual Rows": 1012684,                                                              
                               "Actual Loops": 1,                                                                   
                               "Filter": "(production_year > 2005)",                                                
                               "Rows Removed by Filter": 1513289,                                                   
                               "Shared Hit Blocks": 2488189,                                                        
                               "Shared Read Blocks": 42865,                                                         
                               "Shared Dirtied Blocks": 0,                                                          
                               "Shared Written Blocks": 0,                                                          
                               "Local Hit Blocks": 0,                                                               
                               "Local Read Blocks": 0,                                                              
                               "Local Dirtied Blocks": 0,                                                           
                               "Local Written Blocks": 0,                                                           
                               "Temp Read Blocks": 0,                                                               
                               "Temp Written Blocks": 0                                                             
                             }                                                                                      
                           ]                                                                                        
                         }                                                                                          
                       ]                                                                                            
                     },                                                                                             
                     {                                                                                              
                       "Node Type": "Index Scan",                                                                   
                       "Parent Relationship": "Inner",                                                              
                       "Parallel Aware": false,                                                                     
                       "Scan Direction": "Forward",                                                                 
                       "Index Name": "keyword_pkey",                                                                
                       "Relation Name": "keyword",                                                                  
                       "Alias": "k",                                                                                
                       "Startup Cost": 0.01,                                                                        
                       "Total Cost": 1591.24,                                                                       
                       "Plan Rows": 67,                                                                             
                       "Plan Width": 4,                                                                             
                       "Actual Startup Time": 46.523,                                                               
                       "Actual Total Time": 403.586,                                                                
                       "Actual Rows": 30,                                                                           
                       "Actual Loops": 1,                                                                           
                       "Filter": "(keyword ~~ '%sequel%'::text)",                                                   
                       "Rows Removed by Filter": 134140,                                                            
                       "Shared Hit Blocks": 131177,                                                                 
                       "Shared Read Blocks": 1432,                                                                  
                       "Shared Dirtied Blocks": 0,                                                                  
                       "Shared Written Blocks": 0,                                                                  
                       "Local Hit Blocks": 0,                                                                       
                       "Local Read Blocks": 0,                                                                      
                       "Local Dirtied Blocks": 0,                                                                   
                       "Local Written Blocks": 0,                                                                   
                       "Temp Read Blocks": 0,                                                                       
                       "Temp Written Blocks": 0                                                                     
                     }                                                                                              
                   ]                                                                                                
                 }                                                                                                  
               ]                                                                                                    
             },                                                                                                     
             {                                                                                                      
               "Node Type": "Index Scan",                                                                           
               "Parent Relationship": "Inner",                                                                      
               "Parallel Aware": false,                                                                             
               "Scan Direction": "Forward",                                                                         
               "Index Name": "movie_id_movie_info",                                                                 
               "Relation Name": "movie_info",                                                                       
               "Alias": "mi",                                                                                       
               "Startup Cost": 0.01,                                                                                
               "Total Cost": 620104.07,                                                                             
               "Plan Rows": 154416,                                                                                 
               "Plan Width": 4,                                                                                     
               "Actual Startup Time": 296.332,                                                                      
               "Actual Total Time": 91694.300,                                                                      
               "Actual Rows": 153951,                                                                               
               "Actual Loops": 1,                                                                                   
               "Filter": "(info = ANY ('{Sweden,Norway,Germany,Denmark,Swedish,Denish,Norwegian,German}'::text[]))",
               "Rows Removed by Filter": 14694829,                                                                  
               "Shared Hit Blocks": 9079145,                                                                        
               "Shared Read Blocks": 202423,                                                                        
               "Shared Dirtied Blocks": 0,                                                                          
               "Shared Written Blocks": 0,                                                                          
               "Local Hit Blocks": 0,                                                                               
               "Local Read Blocks": 0,                                                                              
               "Local Dirtied Blocks": 0,                                                                           
               "Local Written Blocks": 0,                                                                           
               "Temp Read Blocks": 0,                                                                               
               "Temp Written Blocks": 0                                                                             
             }                                                                                                      
           ]                                                                                                        
         }                                                                                                          
       ]                                                                                                            
     },                                                                                                             
     "Planning Time": 2152.463,                                                                                     
     "Triggers": [                                                                                                  
     ],                                                                                                             
     "Execution Time": 109313.796                                                                                   
   }                                                                                                                
 ]
