 [                                                                                         
   {                                                                                       
     "Plan": {                                                                             
       "Node Type": "Aggregate",                                                           
       "Strategy": "Plain",                                                                
       "Partial Mode": "Simple",                                                           
       "Parallel Aware": false,                                                            
       "Startup Cost": 701.23,                                                             
       "Total Cost": 701.23,                                                               
       "Plan Rows": 1,                                                                     
       "Plan Width": 32,                                                                   
       "Actual Startup Time": 1614156.777,                                                 
       "Actual Total Time": 1614156.777,                                                   
       "Actual Rows": 1,                                                                   
       "Actual Loops": 1,                                                                  
       "Shared Hit Blocks": 10346213,                                                      
       "Shared Read Blocks": 344620,                                                       
       "Shared Dirtied Blocks": 0,                                                         
       "Shared Written Blocks": 0,                                                         
       "Local Hit Blocks": 0,                                                              
       "Local Read Blocks": 0,                                                             
       "Local Dirtied Blocks": 0,                                                          
       "Local Written Blocks": 0,                                                          
       "Temp Read Blocks": 0,                                                              
       "Temp Written Blocks": 0,                                                           
       "Plans": [                                                                          
         {                                                                                 
           "Node Type": "Nested Loop",                                                     
           "Parent Relationship": "Outer",                                                 
           "Parallel Aware": false,                                                        
           "Join Type": "Inner",                                                           
           "Startup Cost": 0.08,                                                           
           "Total Cost": 701.21,                                                           
           "Plan Rows": 275,                                                               
           "Plan Width": 15,                                                               
           "Actual Startup Time": 1378.016,                                                
           "Actual Total Time": 1613391.791,                                               
           "Actual Rows": 1113120,                                                         
           "Actual Loops": 1,                                                              
           "Inner Unique": true,                                                           
           "Shared Hit Blocks": 10346213,                                                  
           "Shared Read Blocks": 344620,                                                   
           "Shared Dirtied Blocks": 0,                                                     
           "Shared Written Blocks": 0,                                                     
           "Local Hit Blocks": 0,                                                          
           "Local Read Blocks": 0,                                                         
           "Local Dirtied Blocks": 0,                                                      
           "Local Written Blocks": 0,                                                      
           "Temp Read Blocks": 0,                                                          
           "Temp Written Blocks": 0,                                                       
           "Plans": [                                                                      
             {                                                                             
               "Node Type": "Nested Loop",                                                 
               "Parent Relationship": "Outer",                                             
               "Parallel Aware": false,                                                    
               "Join Type": "Inner",                                                       
               "Startup Cost": 0.07,                                                       
               "Total Cost": 696.33,                                                       
               "Plan Rows": 275,                                                           
               "Plan Width": 19,                                                           
               "Actual Startup Time": 1337.379,                                            
               "Actual Total Time": 1575681.395,                                           
               "Actual Rows": 1113120,                                                     
               "Actual Loops": 1,                                                          
               "Inner Unique": false,                                                      
               "Shared Hit Blocks": 5893416,                                               
               "Shared Read Blocks": 340825,                                               
               "Shared Dirtied Blocks": 0,                                                 
               "Shared Written Blocks": 0,                                                 
               "Local Hit Blocks": 0,                                                      
               "Local Read Blocks": 0,                                                     
               "Local Dirtied Blocks": 0,                                                  
               "Local Written Blocks": 0,                                                  
               "Temp Read Blocks": 0,                                                      
               "Temp Written Blocks": 0,                                                   
               "Plans": [                                                                  
                 {                                                                         
                   "Node Type": "Nested Loop",                                             
                   "Parent Relationship": "Outer",                                         
                   "Parallel Aware": false,                                                
                   "Join Type": "Inner",                                                   
                   "Startup Cost": 0.06,                                                   
                   "Total Cost": 694.04,                                                   
                   "Plan Rows": 143,                                                       
                   "Plan Width": 27,                                                       
                   "Actual Startup Time": 92.552,                                          
                   "Actual Total Time": 1562477.853,                                       
                   "Actual Rows": 149494,                                                  
                   "Actual Loops": 1,                                                      
                   "Inner Unique": true,                                                   
                   "Shared Hit Blocks": 5193405,                                           
                   "Shared Read Blocks": 323392,                                           
                   "Shared Dirtied Blocks": 0,                                             
                   "Shared Written Blocks": 0,                                             
                   "Local Hit Blocks": 0,                                                  
                   "Local Read Blocks": 0,                                                 
                   "Local Dirtied Blocks": 0,                                              
                   "Local Written Blocks": 0,                                              
                   "Temp Read Blocks": 0,                                                  
                   "Temp Written Blocks": 0,                                               
                   "Plans": [                                                              
                     {                                                                     
                       "Node Type": "Nested Loop",                                         
                       "Parent Relationship": "Outer",                                     
                       "Parallel Aware": false,                                            
                       "Join Type": "Inner",                                               
                       "Startup Cost": 0.04,                                               
                       "Total Cost": 671.88,                                               
                       "Plan Rows": 1131,                                                  
                       "Plan Width": 16,                                                   
                       "Actual Startup Time": 75.721,                                      
                       "Actual Total Time": 1222500.012,                                   
                       "Actual Rows": 1038393,                                             
                       "Actual Loops": 1,                                                  
                       "Inner Unique": false,                                              
                       "Join Filter": "(t.id = ci.movie_id)",                              
                       "Rows Removed by Join Filter": 0,                                   
                       "Shared Hit Blocks": 1102031,                                       
                       "Shared Read Blocks": 254488,                                       
                       "Shared Dirtied Blocks": 0,                                         
                       "Shared Written Blocks": 0,                                         
                       "Local Hit Blocks": 0,                                              
                       "Local Read Blocks": 0,                                             
                       "Local Dirtied Blocks": 0,                                          
                       "Local Written Blocks": 0,                                          
                       "Temp Read Blocks": 0,                                              
                       "Temp Written Blocks": 0,                                           
                       "Plans": [                                                          
                         {                                                                 
                           "Node Type": "Nested Loop",                                     
                           "Parent Relationship": "Outer",                                 
                           "Parallel Aware": false,                                        
                           "Join Type": "Inner",                                           
                           "Startup Cost": 0.03,                                           
                           "Total Cost": 662.93,                                           
                           "Plan Rows": 34,                                                
                           "Plan Width": 8,                                                
                           "Actual Startup Time": 71.560,                                  
                           "Actual Total Time": 99275.414,                                 
                           "Actual Rows": 41840,                                           
                           "Actual Loops": 1,                                              
                           "Inner Unique": true,                                           
                           "Shared Hit Blocks": 141604,                                    
                           "Shared Read Blocks": 38470,                                    
                           "Shared Dirtied Blocks": 0,                                     
                           "Shared Written Blocks": 0,                                     
                           "Local Hit Blocks": 0,                                          
                           "Local Read Blocks": 0,                                         
                           "Local Dirtied Blocks": 0,                                      
                           "Local Written Blocks": 0,                                      
                           "Temp Read Blocks": 0,                                          
                           "Temp Written Blocks": 0,                                       
                           "Plans": [                                                      
                             {                                                             
                               "Node Type": "Nested Loop",                                 
                               "Parent Relationship": "Outer",                             
                               "Parallel Aware": false,                                    
                               "Join Type": "Inner",                                       
                               "Startup Cost": 0.01,                                       
                               "Total Cost": 661.48,                                       
                               "Plan Rows": 34,                                            
                               "Plan Width": 4,                                            
                               "Actual Startup Time": 53.798,                              
                               "Actual Total Time": 6255.111,                              
                               "Actual Rows": 41840,                                       
                               "Actual Loops": 1,                                          
                               "Inner Unique": false,                                      
                               "Shared Hit Blocks": 5,                                     
                               "Shared Read Blocks": 12602,                                
                               "Shared Dirtied Blocks": 0,                                 
                               "Shared Written Blocks": 0,                                 
                               "Local Hit Blocks": 0,                                      
                               "Local Read Blocks": 0,                                     
                               "Local Dirtied Blocks": 0,                                  
                               "Local Written Blocks": 0,                                  
                               "Temp Read Blocks": 0,                                      
                               "Temp Written Blocks": 0,                                   
                               "Plans": [                                                  
                                 {                                                         
                                   "Node Type": "Seq Scan",                                
                                   "Parent Relationship": "Outer",                         
                                   "Parallel Aware": false,                                
                                   "Relation Name": "keyword",                             
                                   "Alias": "k",                                           
                                   "Startup Cost": 0.00,                                   
                                   "Total Cost": 49.46,                                    
                                   "Plan Rows": 1,                                         
                                   "Plan Width": 4,                                        
                                   "Actual Startup Time": 37.128,                          
                                   "Actual Total Time": 117.623,                           
                                   "Actual Rows": 1,                                       
                                   "Actual Loops": 1,                                      
                                   "Filter": "(keyword = 'character-name-in-title'::text)",
                                   "Rows Removed by Filter": 134169,                       
                                   "Shared Hit Blocks": 2,                                 
                                   "Shared Read Blocks": 947,                              
                                   "Shared Dirtied Blocks": 0,                             
                                   "Shared Written Blocks": 0,                             
                                   "Local Hit Blocks": 0,                                  
                                   "Local Read Blocks": 0,                                 
                                   "Local Dirtied Blocks": 0,                              
                                   "Local Written Blocks": 0,                              
                                   "Temp Read Blocks": 0,                                  
                                   "Temp Written Blocks": 0                                
                                 },                                                        
                                 {                                                         
                                   "Node Type": "Index Scan",                              
                                   "Parent Relationship": "Inner",                         
                                   "Parallel Aware": false,                                
                                   "Scan Direction": "Forward",                            
                                   "Index Name": "keyword_id_movie_keyword",               
                                   "Relation Name": "movie_keyword",                       
                                   "Alias": "mk",                                          
                                   "Startup Cost": 0.01,                                   
                                   "Total Cost": 122.40,                                   
                                   "Plan Rows": 39,                                        
                                   "Plan Width": 8,                                        
                                   "Actual Startup Time": 16.663,                          
                                   "Actual Total Time": 6088.867,                          
                                   "Actual Rows": 41840,                                   
                                   "Actual Loops": 1,                                      
                                   "Index Cond": "(keyword_id = k.id)",                    
                                   "Rows Removed by Index Recheck": 0,                     
                                   "Shared Hit Blocks": 3,                                 
                                   "Shared Read Blocks": 11655,                            
                                   "Shared Dirtied Blocks": 0,                             
                                   "Shared Written Blocks": 0,                             
                                   "Local Hit Blocks": 0,                                  
                                   "Local Read Blocks": 0,                                 
                                   "Local Dirtied Blocks": 0,                              
                                   "Local Written Blocks": 0,                              
                                   "Temp Read Blocks": 0,                                  
                                   "Temp Written Blocks": 0                                
                                 }                                                         
                               ]                                                           
                             },                                                            
                             {                                                             
                               "Node Type": "Index Scan",                                  
                               "Parent Relationship": "Inner",                             
                               "Parallel Aware": false,                                    
                               "Scan Direction": "Forward",                                
                               "Index Name": "title_idx_id",                               
                               "Relation Name": "title",                                   
                               "Alias": "t",                                               
                               "Startup Cost": 0.01,                                       
                               "Total Cost": 0.04,                                         
                               "Plan Rows": 1,                                             
                               "Plan Width": 4,                                            
                               "Actual Startup Time": 2.219,                               
                               "Actual Total Time": 2.219,                                 
                               "Actual Rows": 1,                                           
                               "Actual Loops": 41840,                                      
                               "Index Cond": "(id = mk.movie_id)",                         
                               "Rows Removed by Index Recheck": 0,                         
                               "Shared Hit Blocks": 141599,                                
                               "Shared Read Blocks": 25868,                                
                               "Shared Dirtied Blocks": 0,                                 
                               "Shared Written Blocks": 0,                                 
                               "Local Hit Blocks": 0,                                      
                               "Local Read Blocks": 0,                                     
                               "Local Dirtied Blocks": 0,                                  
                               "Local Written Blocks": 0,                                  
                               "Temp Read Blocks": 0,                                      
                               "Temp Written Blocks": 0                                    
                             }                                                             
                           ]                                                               
                         },                                                                
                         {                                                                 
                           "Node Type": "Index Scan",                                      
                           "Parent Relationship": "Inner",                                 
                           "Parallel Aware": false,                                        
                           "Scan Direction": "Forward",                                    
                           "Index Name": "movie_id_cast_info",                             
                           "Relation Name": "cast_info",                                   
                           "Alias": "ci",                                                  
                           "Startup Cost": 0.02,                                           
                           "Total Cost": 0.26,                                             
                           "Plan Rows": 23,                                                
                           "Plan Width": 8,                                                
                           "Actual Startup Time": 2.578,                                   
                           "Actual Total Time": 26.809,                                    
                           "Actual Rows": 25,                                              
                           "Actual Loops": 41840,                                          
                           "Index Cond": "(movie_id = mk.movie_id)",                       
                           "Rows Removed by Index Recheck": 0,                             
                           "Shared Hit Blocks": 960427,                                    
                           "Shared Read Blocks": 216018,                                   
                           "Shared Dirtied Blocks": 0,                                     
                           "Shared Written Blocks": 0,                                     
                           "Local Hit Blocks": 0,                                          
                           "Local Read Blocks": 0,                                         
                           "Local Dirtied Blocks": 0,                                      
                           "Local Written Blocks": 0,                                      
                           "Temp Read Blocks": 0,                                          
                           "Temp Written Blocks": 0                                        
                         }                                                                 
                       ]                                                                   
                     },                                                                    
                     {                                                                     
                       "Node Type": "Index Scan",                                          
                       "Parent Relationship": "Inner",                                     
                       "Parallel Aware": false,                                            
                       "Scan Direction": "Forward",                                        
                       "Index Name": "name_pkey",                                          
                       "Relation Name": "name",                                            
                       "Alias": "n",                                                       
                       "Startup Cost": 0.01,                                               
                       "Total Cost": 0.02,                                                 
                       "Plan Rows": 1,                                                     
                       "Plan Width": 19,                                                   
                       "Actual Startup Time": 0.325,                                       
                       "Actual Total Time": 0.325,                                         
                       "Actual Rows": 0,                                                   
                       "Actual Loops": 1038393,                                            
                       "Index Cond": "(id = ci.person_id)",                                
                       "Rows Removed by Index Recheck": 0,                                 
                       "Filter": "(name ~~ '%B%'::text)",                                  
                       "Rows Removed by Filter": 1,                                        
                       "Shared Hit Blocks": 4091374,                                       
                       "Shared Read Blocks": 68904,                                        
                       "Shared Dirtied Blocks": 0,                                         
                       "Shared Written Blocks": 0,                                         
                       "Local Hit Blocks": 0,                                              
                       "Local Read Blocks": 0,                                             
                       "Local Dirtied Blocks": 0,                                          
                       "Local Written Blocks": 0,                                          
                       "Temp Read Blocks": 0,                                              
                       "Temp Written Blocks": 0                                            
                     }                                                                     
                   ]                                                                       
                 },                                                                        
                 {                                                                         
                   "Node Type": "Index Scan",                                              
                   "Parent Relationship": "Inner",                                         
                   "Parallel Aware": false,                                                
                   "Scan Direction": "Forward",                                            
                   "Index Name": "movie_id_movie_companies",                               
                   "Relation Name": "movie_companies",                                     
                   "Alias": "mc",                                                          
                   "Startup Cost": 0.01,                                                   
                   "Total Cost": 0.02,                                                     
                   "Plan Rows": 2,                                                         
                   "Plan Width": 8,                                                        
                   "Actual Startup Time": 0.062,                                           
                   "Actual Total Time": 0.083,                                             
                   "Actual Rows": 7,                                                       
                   "Actual Loops": 149494,                                                 
                   "Index Cond": "(movie_id = ci.movie_id)",                               
                   "Rows Removed by Index Recheck": 0,                                     
                   "Shared Hit Blocks": 700011,                                            
                   "Shared Read Blocks": 17433,                                            
                   "Shared Dirtied Blocks": 0,                                             
                   "Shared Written Blocks": 0,                                             
                   "Local Hit Blocks": 0,                                                  
                   "Local Read Blocks": 0,                                                 
                   "Local Dirtied Blocks": 0,                                              
                   "Local Written Blocks": 0,                                              
                   "Temp Read Blocks": 0,                                                  
                   "Temp Written Blocks": 0                                                
                 }                                                                         
               ]                                                                           
             },                                                                            
             {                                                                             
               "Node Type": "Index Scan",                                                  
               "Parent Relationship": "Inner",                                             
               "Parallel Aware": false,                                                    
               "Scan Direction": "Forward",                                                
               "Index Name": "company_name_pkey",                                          
               "Relation Name": "company_name",                                            
               "Alias": "cn",                                                              
               "Startup Cost": 0.01,                                                       
               "Total Cost": 0.02,                                                         
               "Plan Rows": 1,                                                             
               "Plan Width": 4,                                                            
               "Actual Startup Time": 0.032,                                               
               "Actual Total Time": 0.032,                                                 
               "Actual Rows": 1,                                                           
               "Actual Loops": 1113120,                                                    
               "Index Cond": "(id = mc.company_id)",                                       
               "Rows Removed by Index Recheck": 0,                                         
               "Shared Hit Blocks": 4452797,                                               
               "Shared Read Blocks": 3795,                                                 
               "Shared Dirtied Blocks": 0,                                                 
               "Shared Written Blocks": 0,                                                 
               "Local Hit Blocks": 0,                                                      
               "Local Read Blocks": 0,                                                     
               "Local Dirtied Blocks": 0,                                                  
               "Local Written Blocks": 0,                                                  
               "Temp Read Blocks": 0,                                                      
               "Temp Written Blocks": 0                                                    
             }                                                                             
           ]                                                                               
         }                                                                                 
       ]                                                                                   
     },                                                                                    
     "Planning Time": 5718.678,                                                            
     "Triggers": [                                                                         
     ],                                                                                    
     "Execution Time": 1614157.264                                                         
   }                                                                                       
 ]
