 [                                                                                            
   {                                                                                          
     "Plan": {                                                                                
       "Node Type": "Aggregate",                                                              
       "Strategy": "Plain",                                                                   
       "Partial Mode": "Simple",                                                              
       "Parallel Aware": false,                                                               
       "Startup Cost": 5518.38,                                                               
       "Total Cost": 5518.38,                                                                 
       "Plan Rows": 1,                                                                        
       "Plan Width": 96,                                                                      
       "Actual Startup Time": 1541923.040,                                                    
       "Actual Total Time": 1541923.040,                                                      
       "Actual Rows": 1,                                                                      
       "Actual Loops": 1,                                                                     
       "Shared Hit Blocks": 8701067,                                                          
       "Shared Read Blocks": 505816,                                                          
       "Shared Dirtied Blocks": 0,                                                            
       "Shared Written Blocks": 0,                                                            
       "Local Hit Blocks": 0,                                                                 
       "Local Read Blocks": 0,                                                                
       "Local Dirtied Blocks": 0,                                                             
       "Local Written Blocks": 0,                                                             
       "Temp Read Blocks": 0,                                                                 
       "Temp Written Blocks": 0,                                                              
       "Plans": [                                                                             
         {                                                                                    
           "Node Type": "Nested Loop",                                                        
           "Parent Relationship": "Outer",                                                    
           "Parallel Aware": false,                                                           
           "Join Type": "Inner",                                                              
           "Startup Cost": 0.06,                                                              
           "Total Cost": 5518.38,                                                             
           "Plan Rows": 3,                                                                    
           "Plan Width": 65,                                                                  
           "Actual Startup Time": 22176.076,                                                  
           "Actual Total Time": 1541907.064,                                                  
           "Actual Rows": 410,                                                                
           "Actual Loops": 1,                                                                 
           "Inner Unique": true,                                                              
           "Shared Hit Blocks": 8701067,                                                      
           "Shared Read Blocks": 505816,                                                      
           "Shared Dirtied Blocks": 0,                                                        
           "Shared Written Blocks": 0,                                                        
           "Local Hit Blocks": 0,                                                             
           "Local Read Blocks": 0,                                                            
           "Local Dirtied Blocks": 0,                                                         
           "Local Written Blocks": 0,                                                         
           "Temp Read Blocks": 0,                                                             
           "Temp Written Blocks": 0,                                                          
           "Plans": [                                                                         
             {                                                                                
               "Node Type": "Nested Loop",                                                    
               "Parent Relationship": "Outer",                                                
               "Parallel Aware": false,                                                       
               "Join Type": "Inner",                                                          
               "Startup Cost": 0.04,                                                          
               "Total Cost": 5311.10,                                                         
               "Plan Rows": 1985,                                                             
               "Plan Width": 69,                                                              
               "Actual Startup Time": 160.753,                                                
               "Actual Total Time": 1316012.570,                                              
               "Actual Rows": 107339,                                                         
               "Actual Loops": 1,                                                             
               "Inner Unique": false,                                                         
               "Join Filter": "(t.id = ci.movie_id)",                                         
               "Rows Removed by Join Filter": 0,                                              
               "Shared Hit Blocks": 8303533,                                                  
               "Shared Read Blocks": 473153,                                                  
               "Shared Dirtied Blocks": 0,                                                    
               "Shared Written Blocks": 0,                                                    
               "Local Hit Blocks": 0,                                                         
               "Local Read Blocks": 0,                                                        
               "Local Dirtied Blocks": 0,                                                     
               "Local Written Blocks": 0,                                                     
               "Temp Read Blocks": 0,                                                         
               "Temp Written Blocks": 0,                                                      
               "Plans": [                                                                     
                 {                                                                            
                   "Node Type": "Nested Loop",                                                
                   "Parent Relationship": "Outer",                                            
                   "Parallel Aware": false,                                                   
                   "Join Type": "Inner",                                                      
                   "Startup Cost": 0.03,                                                      
                   "Total Cost": 5212.07,                                                     
                   "Plan Rows": 1026,                                                         
                   "Plan Width": 77,                                                          
                   "Actual Startup Time": 114.104,                                            
                   "Actual Total Time": 171791.242,                                           
                   "Actual Rows": 45431,                                                      
                   "Actual Loops": 1,                                                         
                   "Inner Unique": true,                                                      
                   "Join Filter": "(mi.info_type_id = it.id)",                               
                   "Rows Removed by Join Filter": 6884903,                                    
                   "Shared Hit Blocks": 6572028,                                              
                   "Shared Read Blocks": 243897,                                              
                   "Shared Dirtied Blocks": 0,                                                
                   "Shared Written Blocks": 0,                                                
                   "Local Hit Blocks": 0,                                                     
                   "Local Read Blocks": 0,                                                    
                   "Local Dirtied Blocks": 0,                                                 
                   "Local Written Blocks": 0,                                                 
                   "Temp Read Blocks": 0,                                                     
                   "Temp Written Blocks": 0,                                                  
                   "Plans": [                                                                 
                     {                                                                        
                       "Node Type": "Nested Loop",                                            
                       "Parent Relationship": "Outer",                                        
                       "Parallel Aware": false,                                               
                       "Join Type": "Inner",                                                  
                       "Startup Cost": 0.03,                                                  
                       "Total Cost": 5186.01,                                                 
                       "Plan Rows": 115901,                                                   
                       "Plan Width": 81,                                                      
                       "Actual Startup Time": 33.615,                                         
                       "Actual Total Time": 164238.844,                                       
                       "Actual Rows": 6930334,                                                
                       "Actual Loops": 1,                                                     
                       "Inner Unique": false,                                                 
                       "Shared Hit Blocks": 6572027,                                          
                       "Shared Read Blocks": 243897,                                          
                       "Shared Dirtied Blocks": 0,                                            
                       "Shared Written Blocks": 0,                                            
                       "Local Hit Blocks": 0,                                                 
                       "Local Read Blocks": 0,                                                
                       "Local Dirtied Blocks": 0,                                             
                       "Local Written Blocks": 0,                                             
                       "Temp Read Blocks": 0,                                                 
                       "Temp Written Blocks": 0,                                              
                       "Plans": [                                                             
                         {                                                                    
                           "Node Type": "Nested Loop",                                        
                           "Parent Relationship": "Outer",                                    
                           "Parallel Aware": false,                                           
                           "Join Type": "Inner",                                              
                           "Startup Cost": 0.01,                                              
                           "Total Cost": 1998.43,                                             
                           "Plan Rows": 12213,                                                
                           "Plan Width": 31,                                                  
                           "Actual Startup Time": 27.226,                                     
                           "Actual Total Time": 69824.527,                                    
                           "Actual Rows": 459925,                                             
                           "Actual Loops": 1,                                                 
                           "Inner Unique": true,                                              
                           "Shared Hit Blocks": 1798620,                                      
                           "Shared Read Blocks": 50808,                                       
                           "Shared Dirtied Blocks": 0,                                        
                           "Shared Written Blocks": 0,                                        
                           "Local Hit Blocks": 0,                                             
                           "Local Read Blocks": 0,                                            
                           "Local Dirtied Blocks": 0,                                         
                           "Local Written Blocks": 0,                                         
                           "Temp Read Blocks": 0,                                             
                           "Temp Written Blocks": 0,                                          
                           "Plans": [                                                         
                             {                                                                
                               "Node Type": "Nested Loop",                                    
                               "Parent Relationship": "Outer",                                
                               "Parallel Aware": false,                                       
                               "Join Type": "Inner",                                          
                               "Startup Cost": 0.00,                                          
                               "Total Cost": 670.32,                                          
                               "Plan Rows": 12213,                                            
                               "Plan Width": 10,                                              
                               "Actual Startup Time": 0.087,                                  
                               "Actual Total Time": 2263.379,                                 
                               "Actual Rows": 459925,                                         
                               "Actual Loops": 1,                                             
                               "Inner Unique": true,                                          
                               "Join Filter": "(it.id = mi_idx.info_type_id)",               
                               "Rows Removed by Join Filter": 920110,                         
                               "Shared Hit Blocks": 3,                                        
                               "Shared Read Blocks": 8451,                                    
                               "Shared Dirtied Blocks": 0,                                    
                               "Shared Written Blocks": 0,                                    
                               "Local Hit Blocks": 0,                                         
                               "Local Read Blocks": 0,                                        
                               "Local Dirtied Blocks": 0,                                     
                               "Local Written Blocks": 0,                                     
                               "Temp Read Blocks": 0,                                         
                               "Temp Written Blocks": 0,                                      
                               "Plans": [                                                     
                                 {                                                            
                                   "Node Type": "Seq Scan",                                   
                                   "Parent Relationship": "Outer",                            
                                   "Parallel Aware": false,                                   
                                   "Relation Name": "movie_info_idx",                         
                                   "Alias": "mi_idx",                                         
                                   "Startup Cost": 0.00,                                      
                                   "Total Cost": 360.56,                                      
                                   "Plan Rows": 1380035,                                      
                                   "Plan Width": 14,                                          
                                   "Actual Startup Time": 0.014,                              
                                   "Actual Total Time": 569.326,                              
                                   "Actual Rows": 1380035,                                    
                                   "Actual Loops": 1,                                         
                                   "Shared Hit Blocks": 2,                                    
                                   "Shared Read Blocks": 8451,                                
                                   "Shared Dirtied Blocks": 0,                                
                                   "Shared Written Blocks": 0,                                
                                   "Local Hit Blocks": 0,                                     
                                   "Local Read Blocks": 0,                                    
                                   "Local Dirtied Blocks": 0,                                 
                                   "Local Written Blocks": 0,                                 
                                   "Temp Read Blocks": 0,                                     
                                   "Temp Written Blocks": 0                                   
                                 },                                                           
                                 {                                                            
                                   "Node Type": "Materialize",                                
                                   "Parent Relationship": "Inner",                            
                                   "Parallel Aware": false,                                   
                                   "Startup Cost": 0.00,                                      
                                   "Total Cost": 0.05,                                        
                                   "Plan Rows": 1,                                            
                                   "Plan Width": 4,                                           
                                   "Actual Startup Time": 0.000,                              
                                   "Actual Total Time": 0.000,                                
                                   "Actual Rows": 1,                                          
                                   "Actual Loops": 1380035,                                   
                                   "Shared Hit Blocks": 1,                                    
                                   "Shared Read Blocks": 0,                                   
                                   "Shared Dirtied Blocks": 0,                                
                                   "Shared Written Blocks": 0,                                
                                   "Local Hit Blocks": 0,                                     
                                   "Local Read Blocks": 0,                                    
                                   "Local Dirtied Blocks": 0,                                 
                                   "Local Written Blocks": 0,                                 
                                   "Temp Read Blocks": 0,                                     
                                   "Temp Written Blocks": 0,                                  
                                   "Plans": [                                                 
                                     {                                                        
                                       "Node Type": "Seq Scan",                               
                                       "Parent Relationship": "Outer",                        
                                       "Parallel Aware": false,                               
                                       "Relation Name": "info_type",                          
                                       "Alias": "it",                                        
                                       "Startup Cost": 0.00,                                  
                                       "Total Cost": 0.05,                                    
                                       "Plan Rows": 1,                                        
                                       "Plan Width": 4,                                       
                                       "Actual Startup Time": 0.049,                          
                                       "Actual Total Time": 0.055,                            
                                       "Actual Rows": 1,                                      
                                       "Actual Loops": 1,                                     
                                       "Filter": "((info)::text = 'votes'::text)",            
                                       "Rows Removed by Filter": 112,                         
                                       "Shared Hit Blocks": 1,                                
                                       "Shared Read Blocks": 0,                               
                                       "Shared Dirtied Blocks": 0,                            
                                       "Shared Written Blocks": 0,                            
                                       "Local Hit Blocks": 0,                                 
                                       "Local Read Blocks": 0,                                
                                       "Local Dirtied Blocks": 0,                             
                                       "Local Written Blocks": 0,                             
                                       "Temp Read Blocks": 0,                                 
                                       "Temp Written Blocks": 0                               
                                     }                                                        
                                   ]                                                          
                                 }                                                            
                               ]                                                              
                             },                                                               
                             {                                                                
                               "Node Type": "Index Scan",                                     
                               "Parent Relationship": "Inner",                                
                               "Parallel Aware": false,                                       
                               "Scan Direction": "Forward",                                   
                               "Index Name": "title_idx_id",                                  
                               "Relation Name": "title",                                      
                               "Alias": "t",                                                  
                               "Startup Cost": 0.01,                                          
                               "Total Cost": 0.11,                                            
                               "Plan Rows": 1,                                                
                               "Plan Width": 21,                                              
                               "Actual Startup Time": 0.145,                                  
                               "Actual Total Time": 0.145,                                    
                               "Actual Rows": 1,                                              
                               "Actual Loops": 459925,                                        
                               "Index Cond": "(id = mi_idx.movie_id)",                        
                               "Rows Removed by Index Recheck": 0,                            
                               "Shared Hit Blocks": 1798617,                                  
                               "Shared Read Blocks": 42357,                                   
                               "Shared Dirtied Blocks": 0,                                    
                               "Shared Written Blocks": 0,                                    
                               "Local Hit Blocks": 0,                                         
                               "Local Read Blocks": 0,                                        
                               "Local Dirtied Blocks": 0,                                     
                               "Local Written Blocks": 0,                                     
                               "Temp Read Blocks": 0,                                         
                               "Temp Written Blocks": 0                                       
                             }                                                                
                           ]                                                                  
                         },                                                                   
                         {                                                                    
                           "Node Type": "Index Scan",                                         
                           "Parent Relationship": "Inner",                                    
                           "Parallel Aware": false,                                           
                           "Scan Direction": "Forward",                                       
                           "Index Name": "movie_id_movie_info",                               
                           "Relation Name": "movie_info",                                     
                           "Alias": "mi",                                                     
                           "Startup Cost": 0.01,                                              
                           "Total Cost": 0.26,                                                
                           "Plan Rows": 9,                                                    
                           "Plan Width": 50,                                                  
                           "Actual Startup Time": 0.035,                                      
                           "Actual Total Time": 0.195,                                        
                           "Actual Rows": 15,                                                 
                           "Actual Loops": 459925,                                            
                           "Index Cond": "(movie_id = t.id)",                                 
                           "Rows Removed by Index Recheck": 0,                                
                           "Shared Hit Blocks": 4773407,                                      
                           "Shared Read Blocks": 193089,                                      
                           "Shared Dirtied Blocks": 0,                                        
                           "Shared Written Blocks": 0,                                        
                           "Local Hit Blocks": 0,                                             
                           "Local Read Blocks": 0,                                            
                           "Local Dirtied Blocks": 0,                                         
                           "Local Written Blocks": 0,                                         
                           "Temp Read Blocks": 0,                                             
                           "Temp Written Blocks": 0                                           
                         }                                                                    
                       ]                                                                      
                     },                                                                       
                     {                                                                        
                       "Node Type": "Materialize",                                            
                       "Parent Relationship": "Inner",                                        
                       "Parallel Aware": false,                                               
                       "Startup Cost": 0.00,                                                  
                       "Total Cost": 0.05,                                                    
                       "Plan Rows": 1,                                                        
                       "Plan Width": 4,                                                       
                       "Actual Startup Time": 0.000,                                          
                       "Actual Total Time": 0.000,                                            
                       "Actual Rows": 1,                                                      
                       "Actual Loops": 6930334,                                               
                       "Shared Hit Blocks": 1,                                                
                       "Shared Read Blocks": 0,                                               
                       "Shared Dirtied Blocks": 0,                                            
                       "Shared Written Blocks": 0,                                            
                       "Local Hit Blocks": 0,                                                 
                       "Local Read Blocks": 0,                                                
                       "Local Dirtied Blocks": 0,                                             
                       "Local Written Blocks": 0,                                             
                       "Temp Read Blocks": 0,                                                 
                       "Temp Written Blocks": 0,                                              
                       "Plans": [                                                             
                         {                                                                    
                           "Node Type": "Seq Scan",                                           
                           "Parent Relationship": "Outer",                                    
                           "Parallel Aware": false,                                           
                           "Relation Name": "info_type",                                      
                           "Alias": "it",                                                    
                           "Startup Cost": 0.00,                                              
                           "Total Cost": 0.05,                                                
                           "Plan Rows": 1,                                                    
                           "Plan Width": 4,                                                   
                           "Actual Startup Time": 0.061,                                      
                           "Actual Total Time": 0.066,                                        
                           "Actual Rows": 1,                                                  
                           "Actual Loops": 1,                                                 
                           "Filter": "((info)::text = 'budget'::text)",                       
                           "Rows Removed by Filter": 112,                                     
                           "Shared Hit Blocks": 1,                                            
                           "Shared Read Blocks": 0,                                           
                           "Shared Dirtied Blocks": 0,                                        
                           "Shared Written Blocks": 0,                                        
                           "Local Hit Blocks": 0,                                             
                           "Local Read Blocks": 0,                                            
                           "Local Dirtied Blocks": 0,                                         
                           "Local Written Blocks": 0,                                         
                           "Temp Read Blocks": 0,                                             
                           "Temp Written Blocks": 0                                           
                         }                                                                    
                       ]                                                                      
                     }                                                                        
                   ]                                                                          
                 },                                                                           
                 {                                                                            
                   "Node Type": "Index Scan",                                                 
                   "Parent Relationship": "Inner",                                            
                   "Parallel Aware": false,                                                   
                   "Scan Direction": "Forward",                                               
                   "Index Name": "movie_id_cast_info",                                        
                   "Relation Name": "cast_info",                                              
                   "Alias": "ci",                                                             
                   "Startup Cost": 0.02,                                                      
                   "Total Cost": 0.10,                                                        
                   "Plan Rows": 2,                                                            
                   "Plan Width": 8,                                                           
                   "Actual Startup Time": 16.340,                                             
                   "Actual Total Time": 25.180,                                               
                   "Actual Rows": 2,                                                          
                   "Actual Loops": 45431,                                                     
                   "Index Cond": "(movie_id = mi.movie_id)",                                  
                   "Rows Removed by Index Recheck": 0,                                        
                   "Filter": "(note = ANY ('{(producer),\"(executive producer)\"}'::text[]))",
                   "Rows Removed by Filter": 38,                                              
                   "Shared Hit Blocks": 1731505,                                              
                   "Shared Read Blocks": 229256,                                              
                   "Shared Dirtied Blocks": 0,                                                
                   "Shared Written Blocks": 0,                                                
                   "Local Hit Blocks": 0,                                                     
                   "Local Read Blocks": 0,                                                    
                   "Local Dirtied Blocks": 0,                                                 
                   "Local Written Blocks": 0,                                                 
                   "Temp Read Blocks": 0,                                                     
                   "Temp Written Blocks": 0                                                   
                 }                                                                            
               ]                                                                              
             },                                                                               
             {                                                                                
               "Node Type": "Index Scan",                                                     
               "Parent Relationship": "Inner",                                                
               "Parallel Aware": false,                                                       
               "Scan Direction": "Forward",                                                   
               "Index Name": "name_pkey",                                                     
               "Relation Name": "name",                                                       
               "Alias": "n",                                                                  
               "Startup Cost": 0.01,                                                          
               "Total Cost": 0.10,                                                            
               "Plan Rows": 1,                                                                
               "Plan Width": 4,                                                               
               "Actual Startup Time": 2.102,                                                  
               "Actual Total Time": 2.102,                                                    
               "Actual Rows": 0,                                                              
               "Actual Loops": 107339,                                                        
               "Index Cond": "(id = ci.person_id)",                                           
               "Rows Removed by Index Recheck": 0,                                            
               "Filter": "((name ~~ '%Tim%'::text) AND ((gender)::text = 'm'::text))",        
               "Rows Removed by Filter": 1,                                                   
               "Shared Hit Blocks": 397534,                                                   
               "Shared Read Blocks": 32663,                                                   
               "Shared Dirtied Blocks": 0,                                                    
               "Shared Written Blocks": 0,                                                    
               "Local Hit Blocks": 0,                                                         
               "Local Read Blocks": 0,                                                        
               "Local Dirtied Blocks": 0,                                                     
               "Local Written Blocks": 0,                                                     
               "Temp Read Blocks": 0,                                                         
               "Temp Written Blocks": 0                                                       
             }                                                                                
           ]                                                                                  
         }                                                                                    
       ]                                                                                      
     },                                                                                       
     "Planning Time": 5583.714,                                                               
     "Triggers": [                                                                            
     ],                                                                                       
     "Execution Time": 1542000.607                                                            
   }                                                                                          
 ]
