 [                                                                                 
   {                                                                               
     "Plan": {                                                                     
       "Node Type": "Aggregate",                                                   
       "Strategy": "Plain",                                                        
       "Partial Mode": "Simple",                                                   
       "Parallel Aware": false,                                                    
       "Startup Cost": 666.02,                                                     
       "Total Cost": 666.02,                                                       
       "Plan Rows": 1,                                                             
       "Plan Width": 32,                                                           
       "Actual Startup Time": 28567.906,                                           
       "Actual Total Time": 28567.907,                                             
       "Actual Rows": 1,                                                           
       "Actual Loops": 1,                                                          
       "Shared Hit Blocks": 777995,                                                
       "Shared Read Blocks": 39304,                                                
       "Shared Dirtied Blocks": 0,                                                 
       "Shared Written Blocks": 0,                                                 
       "Local Hit Blocks": 0,                                                      
       "Local Read Blocks": 0,                                                     
       "Local Dirtied Blocks": 0,                                                  
       "Local Written Blocks": 0,                                                  
       "Temp Read Blocks": 0,                                                      
       "Temp Written Blocks": 0,                                                   
       "Plans": [                                                                  
         {                                                                         
           "Node Type": "Nested Loop",                                             
           "Parent Relationship": "Outer",                                         
           "Parallel Aware": false,                                                
           "Join Type": "Inner",                                                   
           "Startup Cost": 0.05,                                                   
           "Total Cost": 666.02,                                                   
           "Plan Rows": 2,                                                         
           "Plan Width": 17,                                                       
           "Actual Startup Time": 579.170,                                         
           "Actual Total Time": 28546.535,                                         
           "Actual Rows": 5228,                                                    
           "Actual Loops": 1,                                                      
           "Inner Unique": true,                                                   
           "Join Filter": "(mc.movie_id = t.id)",                                  
           "Rows Removed by Join Filter": 0,                                       
           "Shared Hit Blocks": 777995,                                            
           "Shared Read Blocks": 39304,                                            
           "Shared Dirtied Blocks": 0,                                             
           "Shared Written Blocks": 0,                                             
           "Local Hit Blocks": 0,                                                  
           "Local Read Blocks": 0,                                                 
           "Local Dirtied Blocks": 0,                                              
           "Local Written Blocks": 0,                                              
           "Temp Read Blocks": 0,                                                  
           "Temp Written Blocks": 0,                                               
           "Plans": [                                                              
             {                                                                     
               "Node Type": "Nested Loop",                                         
               "Parent Relationship": "Outer",                                     
               "Parallel Aware": false,                                            
               "Join Type": "Inner",                                               
               "Startup Cost": 0.04,                                               
               "Total Cost": 665.93,                                               
               "Plan Rows": 2,                                                     
               "Plan Width": 8,                                                    
               "Actual Startup Time": 533.751,                                     
               "Actual Total Time": 15782.133,                                     
               "Actual Rows": 5228,                                                
               "Actual Loops": 1,                                                  
               "Inner Unique": true,                                               
               "Shared Hit Blocks": 760899,                                        
               "Shared Read Blocks": 35476,                                        
               "Shared Dirtied Blocks": 0,                                         
               "Shared Written Blocks": 0,                                         
               "Local Hit Blocks": 0,                                              
               "Local Read Blocks": 0,                                             
               "Local Dirtied Blocks": 0,                                          
               "Local Written Blocks": 0,                                          
               "Temp Read Blocks": 0,                                              
               "Temp Written Blocks": 0,                                           
               "Plans": [                                                          
                 {                                                                 
                   "Node Type": "Nested Loop",                                     
                   "Parent Relationship": "Outer",                                 
                   "Parallel Aware": false,                                        
                   "Join Type": "Inner",                                           
                   "Startup Cost": 0.03,                                           
                   "Total Cost": 662.55,                                           
                   "Plan Rows": 190,                                               
                   "Plan Width": 12,                                               
                   "Actual Startup Time": 59.088,                                  
                   "Actual Total Time": 8170.726,                                  
                   "Actual Rows": 148552,                                          
                   "Actual Loops": 1,                                              
                   "Inner Unique": false,                                          
                   "Shared Hit Blocks": 169756,                                    
                   "Shared Read Blocks": 31669,                                    
                   "Shared Dirtied Blocks": 0,                                     
                   "Shared Written Blocks": 0,                                     
                   "Local Hit Blocks": 0,                                          
                   "Local Read Blocks": 0,                                         
                   "Local Dirtied Blocks": 0,                                      
                   "Local Written Blocks": 0,                                      
                   "Temp Read Blocks": 0,                                          
                   "Temp Written Blocks": 0,                                       
                   "Plans": [                                                      
                     {                                                             
                       "Node Type": "Nested Loop",                                 
                       "Parent Relationship": "Outer",                             
                       "Parallel Aware": false,                                    
                       "Join Type": "Inner",                                       
                       "Startup Cost": 0.01,                                       
                       "Total Cost": 661.48,                                       
                       "Plan Rows": 34,                                            
                       "Plan Width": 4,                                            
                       "Actual Startup Time": 58.425,                              
                       "Actual Total Time": 4553.630,                              
                       "Actual Rows": 41840,                                       
                       "Actual Loops": 1,                                          
                       "Inner Unique": false,                                      
                       "Shared Hit Blocks": 5,                                     
                       "Shared Read Blocks": 12602,                                
                       "Shared Dirtied Blocks": 0,                                 
                       "Shared Written Blocks": 0,                                 
                       "Local Hit Blocks": 0,                                      
                       "Local Read Blocks": 0,                                     
                       "Local Dirtied Blocks": 0,                                  
                       "Local Written Blocks": 0,                                  
                       "Temp Read Blocks": 0,                                      
                       "Temp Written Blocks": 0,                                   
                       "Plans": [                                                  
                         {                                                         
                           "Node Type": "Seq Scan",                                
                           "Parent Relationship": "Outer",                         
                           "Parallel Aware": false,                                
                           "Relation Name": "keyword",                             
                           "Alias": "k",                                           
                           "Startup Cost": 0.00,                                   
                           "Total Cost": 49.46,                                    
                           "Plan Rows": 1,                                         
                           "Plan Width": 4,                                        
                           "Actual Startup Time": 33.464,                          
                           "Actual Total Time": 115.341,                           
                           "Actual Rows": 1,                                       
                           "Actual Loops": 1,                                      
                           "Filter": "(keyword = 'character-name-in-title'::text)",
                           "Rows Removed by Filter": 134169,                       
                           "Shared Hit Blocks": 2,                                 
                           "Shared Read Blocks": 947,                              
                           "Shared Dirtied Blocks": 0,                             
                           "Shared Written Blocks": 0,                             
                           "Local Hit Blocks": 0,                                  
                           "Local Read Blocks": 0,                                 
                           "Local Dirtied Blocks": 0,                              
                           "Local Written Blocks": 0,                              
                           "Temp Read Blocks": 0,                                  
                           "Temp Written Blocks": 0                                
                         },                                                        
                         {                                                         
                           "Node Type": "Index Scan",                              
                           "Parent Relationship": "Inner",                         
                           "Parallel Aware": false,                                
                           "Scan Direction": "Forward",                            
                           "Index Name": "keyword_id_movie_keyword",               
                           "Relation Name": "movie_keyword",                       
                           "Alias": "mk",                                          
                           "Startup Cost": 0.01,                                   
                           "Total Cost": 122.40,                                   
                           "Plan Rows": 39,                                        
                           "Plan Width": 8,                                        
                           "Actual Startup Time": 24.951,                          
                           "Actual Total Time": 4420.624,                          
                           "Actual Rows": 41840,                                   
                           "Actual Loops": 1,                                      
                           "Index Cond": "(keyword_id = k.id)",                    
                           "Rows Removed by Index Recheck": 0,                     
                           "Shared Hit Blocks": 3,                                 
                           "Shared Read Blocks": 11655,                            
                           "Shared Dirtied Blocks": 0,                             
                           "Shared Written Blocks": 0,                             
                           "Local Hit Blocks": 0,                                  
                           "Local Read Blocks": 0,                                 
                           "Local Dirtied Blocks": 0,                              
                           "Local Written Blocks": 0,                              
                           "Temp Read Blocks": 0,                                  
                           "Temp Written Blocks": 0                                
                         }                                                         
                       ]                                                           
                     },                                                            
                     {                                                             
                       "Node Type": "Index Scan",                                  
                       "Parent Relationship": "Inner",                             
                       "Parallel Aware": false,                                    
                       "Scan Direction": "Forward",                                
                       "Index Name": "movie_id_movie_companies",                   
                       "Relation Name": "movie_companies",                         
                       "Alias": "mc",                                              
                       "Startup Cost": 0.01,                                       
                       "Total Cost": 0.03,                                         
                       "Plan Rows": 2,                                             
                       "Plan Width": 8,                                            
                       "Actual Startup Time": 0.068,                               
                       "Actual Total Time": 0.084,                                 
                       "Actual Rows": 4,                                           
                       "Actual Loops": 41840,                                      
                       "Index Cond": "(movie_id = mk.movie_id)",                   
                       "Rows Removed by Index Recheck": 0,                         
                       "Shared Hit Blocks": 169751,                                
                       "Shared Read Blocks": 19067,                                
                       "Shared Dirtied Blocks": 0,                                 
                       "Shared Written Blocks": 0,                                 
                       "Local Hit Blocks": 0,                                      
                       "Local Read Blocks": 0,                                     
                       "Local Dirtied Blocks": 0,                                  
                       "Local Written Blocks": 0,                                  
                       "Temp Read Blocks": 0,                                      
                       "Temp Written Blocks": 0                                    
                     }                                                             
                   ]                                                               
                 },                                                                
                 {                                                                 
                   "Node Type": "Index Scan",                                      
                   "Parent Relationship": "Inner",                                 
                   "Parallel Aware": false,                                        
                   "Scan Direction": "Forward",                                    
                   "Index Name": "company_name_pkey",                              
                   "Relation Name": "company_name",                                
                   "Alias": "cn",                                                  
                   "Startup Cost": 0.01,                                           
                   "Total Cost": 0.02,                                             
                   "Plan Rows": 1,                                                 
                   "Plan Width": 4,                                                
                   "Actual Startup Time": 0.050,                                   
                   "Actual Total Time": 0.050,                                     
                   "Actual Rows": 0,                                               
                   "Actual Loops": 148552,                                         
                   "Index Cond": "(id = mc.company_id)",                           
                   "Rows Removed by Index Recheck": 0,                             
                   "Filter": "((country_code)::text = '[nl]'::text)",              
                   "Rows Removed by Filter": 1,                                    
                   "Shared Hit Blocks": 591143,                                    
                   "Shared Read Blocks": 3807,                                     
                   "Shared Dirtied Blocks": 0,                                     
                   "Shared Written Blocks": 0,                                     
                   "Local Hit Blocks": 0,                                          
                   "Local Read Blocks": 0,                                         
                   "Local Dirtied Blocks": 0,                                      
                   "Local Written Blocks": 0,                                      
                   "Temp Read Blocks": 0,                                          
                   "Temp Written Blocks": 0                                        
                 }                                                                 
               ]                                                                   
             },                                                                    
             {                                                                     
               "Node Type": "Index Scan",                                          
               "Parent Relationship": "Inner",                                     
               "Parallel Aware": false,                                            
               "Scan Direction": "Forward",                                        
               "Index Name": "title_idx_id",                                       
               "Relation Name": "title",                                           
               "Alias": "t",                                                       
               "Startup Cost": 0.01,                                               
               "Total Cost": 0.04,                                                 
               "Plan Rows": 1,                                                     
               "Plan Width": 21,                                                   
               "Actual Startup Time": 2.439,                                       
               "Actual Total Time": 2.439,                                         
               "Actual Rows": 1,                                                   
               "Actual Loops": 5228,                                               
               "Index Cond": "(id = mk.movie_id)",                                 
               "Rows Removed by Index Recheck": 0,                                 
               "Shared Hit Blocks": 17096,                                         
               "Shared Read Blocks": 3828,                                         
               "Shared Dirtied Blocks": 0,                                         
               "Shared Written Blocks": 0,                                         
               "Local Hit Blocks": 0,                                              
               "Local Read Blocks": 0,                                             
               "Local Dirtied Blocks": 0,                                          
               "Local Written Blocks": 0,                                          
               "Temp Read Blocks": 0,                                              
               "Temp Written Blocks": 0                                            
             }                                                                     
           ]                                                                       
         }                                                                         
       ]                                                                           
     },                                                                            
     "Planning Time": 2318.195,                                                    
     "Triggers": [                                                                 
     ],                                                                            
     "Execution Time": 28568.539                                                   
   }                                                                               
 ]
